// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: numCurrency.proto

package com.protos.numCurrency;

public final class NumCurrency {
  private NumCurrency() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NumCurrencyACKOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.numCurrency.NumCurrencyACK)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *符文货币
     * </pre>
     *
     * <code>uint64 runeCurrency = 1;</code>
     */
    long getRuneCurrency();

    /**
     * <pre>
     *预言塔货币
     * </pre>
     *
     * <code>uint64 predictedShop = 2;</code>
     */
    long getPredictedShop();

    /**
     * <pre>
     *声望货币
     * </pre>
     *
     * <code>uint64 influenceCurrency = 3;</code>
     */
    long getInfluenceCurrency();
  }
  /**
   * <pre>
   *数值道具类型
   * </pre>
   *
   * Protobuf type {@code com.protos.numCurrency.NumCurrencyACK}
   */
  public  static final class NumCurrencyACK extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.numCurrency.NumCurrencyACK)
      NumCurrencyACKOrBuilder {
    // Use NumCurrencyACK.newBuilder() to construct.
    private NumCurrencyACK(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NumCurrencyACK() {
      runeCurrency_ = 0L;
      predictedShop_ = 0L;
      influenceCurrency_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NumCurrencyACK(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              runeCurrency_ = input.readUInt64();
              break;
            }
            case 16: {

              predictedShop_ = input.readUInt64();
              break;
            }
            case 24: {

              influenceCurrency_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.numCurrency.NumCurrency.internal_static_com_protos_numCurrency_NumCurrencyACK_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.numCurrency.NumCurrency.internal_static_com_protos_numCurrency_NumCurrencyACK_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.numCurrency.NumCurrency.NumCurrencyACK.class, com.protos.numCurrency.NumCurrency.NumCurrencyACK.Builder.class);
    }

    public static final int RUNECURRENCY_FIELD_NUMBER = 1;
    private long runeCurrency_;
    /**
     * <pre>
     *符文货币
     * </pre>
     *
     * <code>uint64 runeCurrency = 1;</code>
     */
    public long getRuneCurrency() {
      return runeCurrency_;
    }

    public static final int PREDICTEDSHOP_FIELD_NUMBER = 2;
    private long predictedShop_;
    /**
     * <pre>
     *预言塔货币
     * </pre>
     *
     * <code>uint64 predictedShop = 2;</code>
     */
    public long getPredictedShop() {
      return predictedShop_;
    }

    public static final int INFLUENCECURRENCY_FIELD_NUMBER = 3;
    private long influenceCurrency_;
    /**
     * <pre>
     *声望货币
     * </pre>
     *
     * <code>uint64 influenceCurrency = 3;</code>
     */
    public long getInfluenceCurrency() {
      return influenceCurrency_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (runeCurrency_ != 0L) {
        output.writeUInt64(1, runeCurrency_);
      }
      if (predictedShop_ != 0L) {
        output.writeUInt64(2, predictedShop_);
      }
      if (influenceCurrency_ != 0L) {
        output.writeUInt64(3, influenceCurrency_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (runeCurrency_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, runeCurrency_);
      }
      if (predictedShop_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, predictedShop_);
      }
      if (influenceCurrency_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, influenceCurrency_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.numCurrency.NumCurrency.NumCurrencyACK)) {
        return super.equals(obj);
      }
      com.protos.numCurrency.NumCurrency.NumCurrencyACK other = (com.protos.numCurrency.NumCurrency.NumCurrencyACK) obj;

      boolean result = true;
      result = result && (getRuneCurrency()
          == other.getRuneCurrency());
      result = result && (getPredictedShop()
          == other.getPredictedShop());
      result = result && (getInfluenceCurrency()
          == other.getInfluenceCurrency());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RUNECURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRuneCurrency());
      hash = (37 * hash) + PREDICTEDSHOP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPredictedShop());
      hash = (37 * hash) + INFLUENCECURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInfluenceCurrency());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.numCurrency.NumCurrency.NumCurrencyACK prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *数值道具类型
     * </pre>
     *
     * Protobuf type {@code com.protos.numCurrency.NumCurrencyACK}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.numCurrency.NumCurrencyACK)
        com.protos.numCurrency.NumCurrency.NumCurrencyACKOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.numCurrency.NumCurrency.internal_static_com_protos_numCurrency_NumCurrencyACK_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.numCurrency.NumCurrency.internal_static_com_protos_numCurrency_NumCurrencyACK_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.numCurrency.NumCurrency.NumCurrencyACK.class, com.protos.numCurrency.NumCurrency.NumCurrencyACK.Builder.class);
      }

      // Construct using com.protos.numCurrency.NumCurrency.NumCurrencyACK.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        runeCurrency_ = 0L;

        predictedShop_ = 0L;

        influenceCurrency_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.numCurrency.NumCurrency.internal_static_com_protos_numCurrency_NumCurrencyACK_descriptor;
      }

      public com.protos.numCurrency.NumCurrency.NumCurrencyACK getDefaultInstanceForType() {
        return com.protos.numCurrency.NumCurrency.NumCurrencyACK.getDefaultInstance();
      }

      public com.protos.numCurrency.NumCurrency.NumCurrencyACK build() {
        com.protos.numCurrency.NumCurrency.NumCurrencyACK result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.numCurrency.NumCurrency.NumCurrencyACK buildPartial() {
        com.protos.numCurrency.NumCurrency.NumCurrencyACK result = new com.protos.numCurrency.NumCurrency.NumCurrencyACK(this);
        result.runeCurrency_ = runeCurrency_;
        result.predictedShop_ = predictedShop_;
        result.influenceCurrency_ = influenceCurrency_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.numCurrency.NumCurrency.NumCurrencyACK) {
          return mergeFrom((com.protos.numCurrency.NumCurrency.NumCurrencyACK)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.numCurrency.NumCurrency.NumCurrencyACK other) {
        if (other == com.protos.numCurrency.NumCurrency.NumCurrencyACK.getDefaultInstance()) return this;
        if (other.getRuneCurrency() != 0L) {
          setRuneCurrency(other.getRuneCurrency());
        }
        if (other.getPredictedShop() != 0L) {
          setPredictedShop(other.getPredictedShop());
        }
        if (other.getInfluenceCurrency() != 0L) {
          setInfluenceCurrency(other.getInfluenceCurrency());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.numCurrency.NumCurrency.NumCurrencyACK parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.numCurrency.NumCurrency.NumCurrencyACK) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long runeCurrency_ ;
      /**
       * <pre>
       *符文货币
       * </pre>
       *
       * <code>uint64 runeCurrency = 1;</code>
       */
      public long getRuneCurrency() {
        return runeCurrency_;
      }
      /**
       * <pre>
       *符文货币
       * </pre>
       *
       * <code>uint64 runeCurrency = 1;</code>
       */
      public Builder setRuneCurrency(long value) {
        
        runeCurrency_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *符文货币
       * </pre>
       *
       * <code>uint64 runeCurrency = 1;</code>
       */
      public Builder clearRuneCurrency() {
        
        runeCurrency_ = 0L;
        onChanged();
        return this;
      }

      private long predictedShop_ ;
      /**
       * <pre>
       *预言塔货币
       * </pre>
       *
       * <code>uint64 predictedShop = 2;</code>
       */
      public long getPredictedShop() {
        return predictedShop_;
      }
      /**
       * <pre>
       *预言塔货币
       * </pre>
       *
       * <code>uint64 predictedShop = 2;</code>
       */
      public Builder setPredictedShop(long value) {
        
        predictedShop_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *预言塔货币
       * </pre>
       *
       * <code>uint64 predictedShop = 2;</code>
       */
      public Builder clearPredictedShop() {
        
        predictedShop_ = 0L;
        onChanged();
        return this;
      }

      private long influenceCurrency_ ;
      /**
       * <pre>
       *声望货币
       * </pre>
       *
       * <code>uint64 influenceCurrency = 3;</code>
       */
      public long getInfluenceCurrency() {
        return influenceCurrency_;
      }
      /**
       * <pre>
       *声望货币
       * </pre>
       *
       * <code>uint64 influenceCurrency = 3;</code>
       */
      public Builder setInfluenceCurrency(long value) {
        
        influenceCurrency_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *声望货币
       * </pre>
       *
       * <code>uint64 influenceCurrency = 3;</code>
       */
      public Builder clearInfluenceCurrency() {
        
        influenceCurrency_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.numCurrency.NumCurrencyACK)
    }

    // @@protoc_insertion_point(class_scope:com.protos.numCurrency.NumCurrencyACK)
    private static final com.protos.numCurrency.NumCurrency.NumCurrencyACK DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.numCurrency.NumCurrency.NumCurrencyACK();
    }

    public static com.protos.numCurrency.NumCurrency.NumCurrencyACK getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NumCurrencyACK>
        PARSER = new com.google.protobuf.AbstractParser<NumCurrencyACK>() {
      public NumCurrencyACK parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NumCurrencyACK(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NumCurrencyACK> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NumCurrencyACK> getParserForType() {
      return PARSER;
    }

    public com.protos.numCurrency.NumCurrency.NumCurrencyACK getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_numCurrency_NumCurrencyACK_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_numCurrency_NumCurrencyACK_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021numCurrency.proto\022\026com.protos.numCurre" +
      "ncy\"X\n\016NumCurrencyACK\022\024\n\014runeCurrency\030\001 " +
      "\001(\004\022\025\n\rpredictedShop\030\002 \001(\004\022\031\n\021influenceC" +
      "urrency\030\003 \001(\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protos_numCurrency_NumCurrencyACK_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_numCurrency_NumCurrencyACK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_numCurrency_NumCurrencyACK_descriptor,
        new java.lang.String[] { "RuneCurrency", "PredictedShop", "InfluenceCurrency", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
