// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonthCard.proto

package com.protos.monthCard;

public final class MonthCard {
  private MonthCard() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MonthCardInfoREQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.monthCard.MonthCardInfoREQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *暂时无用，可以不传
     * </pre>
     *
     * <code>uint32 default = 1;</code>
     */
    int getDefault();
  }
  /**
   * <pre>
   *请求月卡信息
   * </pre>
   *
   * Protobuf type {@code com.protos.monthCard.MonthCardInfoREQ}
   */
  public  static final class MonthCardInfoREQ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.monthCard.MonthCardInfoREQ)
      MonthCardInfoREQOrBuilder {
    // Use MonthCardInfoREQ.newBuilder() to construct.
    private MonthCardInfoREQ(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonthCardInfoREQ() {
      default_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MonthCardInfoREQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              default_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoREQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoREQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.monthCard.MonthCard.MonthCardInfoREQ.class, com.protos.monthCard.MonthCard.MonthCardInfoREQ.Builder.class);
    }

    public static final int DEFAULT_FIELD_NUMBER = 1;
    private int default_;
    /**
     * <pre>
     *暂时无用，可以不传
     * </pre>
     *
     * <code>uint32 default = 1;</code>
     */
    public int getDefault() {
      return default_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (default_ != 0) {
        output.writeUInt32(1, default_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (default_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, default_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.monthCard.MonthCard.MonthCardInfoREQ)) {
        return super.equals(obj);
      }
      com.protos.monthCard.MonthCard.MonthCardInfoREQ other = (com.protos.monthCard.MonthCard.MonthCardInfoREQ) obj;

      boolean result = true;
      result = result && (getDefault()
          == other.getDefault());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEFAULT_FIELD_NUMBER;
      hash = (53 * hash) + getDefault();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.monthCard.MonthCard.MonthCardInfoREQ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求月卡信息
     * </pre>
     *
     * Protobuf type {@code com.protos.monthCard.MonthCardInfoREQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.monthCard.MonthCardInfoREQ)
        com.protos.monthCard.MonthCard.MonthCardInfoREQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoREQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoREQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.monthCard.MonthCard.MonthCardInfoREQ.class, com.protos.monthCard.MonthCard.MonthCardInfoREQ.Builder.class);
      }

      // Construct using com.protos.monthCard.MonthCard.MonthCardInfoREQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        default_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoREQ_descriptor;
      }

      public com.protos.monthCard.MonthCard.MonthCardInfoREQ getDefaultInstanceForType() {
        return com.protos.monthCard.MonthCard.MonthCardInfoREQ.getDefaultInstance();
      }

      public com.protos.monthCard.MonthCard.MonthCardInfoREQ build() {
        com.protos.monthCard.MonthCard.MonthCardInfoREQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.monthCard.MonthCard.MonthCardInfoREQ buildPartial() {
        com.protos.monthCard.MonthCard.MonthCardInfoREQ result = new com.protos.monthCard.MonthCard.MonthCardInfoREQ(this);
        result.default_ = default_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.monthCard.MonthCard.MonthCardInfoREQ) {
          return mergeFrom((com.protos.monthCard.MonthCard.MonthCardInfoREQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.monthCard.MonthCard.MonthCardInfoREQ other) {
        if (other == com.protos.monthCard.MonthCard.MonthCardInfoREQ.getDefaultInstance()) return this;
        if (other.getDefault() != 0) {
          setDefault(other.getDefault());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.monthCard.MonthCard.MonthCardInfoREQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.monthCard.MonthCard.MonthCardInfoREQ) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int default_ ;
      /**
       * <pre>
       *暂时无用，可以不传
       * </pre>
       *
       * <code>uint32 default = 1;</code>
       */
      public int getDefault() {
        return default_;
      }
      /**
       * <pre>
       *暂时无用，可以不传
       * </pre>
       *
       * <code>uint32 default = 1;</code>
       */
      public Builder setDefault(int value) {
        
        default_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *暂时无用，可以不传
       * </pre>
       *
       * <code>uint32 default = 1;</code>
       */
      public Builder clearDefault() {
        
        default_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.monthCard.MonthCardInfoREQ)
    }

    // @@protoc_insertion_point(class_scope:com.protos.monthCard.MonthCardInfoREQ)
    private static final com.protos.monthCard.MonthCard.MonthCardInfoREQ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.monthCard.MonthCard.MonthCardInfoREQ();
    }

    public static com.protos.monthCard.MonthCard.MonthCardInfoREQ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonthCardInfoREQ>
        PARSER = new com.google.protobuf.AbstractParser<MonthCardInfoREQ>() {
      public MonthCardInfoREQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MonthCardInfoREQ(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonthCardInfoREQ> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonthCardInfoREQ> getParserForType() {
      return PARSER;
    }

    public com.protos.monthCard.MonthCard.MonthCardInfoREQ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MonthCardInfoACKOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.monthCard.MonthCardInfoACK)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    java.util.List<com.protos.monthCard.MonthCard.MonthCardInfo> 
        getMonthCardsList();
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    com.protos.monthCard.MonthCard.MonthCardInfo getMonthCards(int index);
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    int getMonthCardsCount();
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    java.util.List<? extends com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder> 
        getMonthCardsOrBuilderList();
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder getMonthCardsOrBuilder(
        int index);
  }
  /**
   * <pre>
   *月卡信息返回
   * </pre>
   *
   * Protobuf type {@code com.protos.monthCard.MonthCardInfoACK}
   */
  public  static final class MonthCardInfoACK extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.monthCard.MonthCardInfoACK)
      MonthCardInfoACKOrBuilder {
    // Use MonthCardInfoACK.newBuilder() to construct.
    private MonthCardInfoACK(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonthCardInfoACK() {
      monthCards_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MonthCardInfoACK(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                monthCards_ = new java.util.ArrayList<com.protos.monthCard.MonthCard.MonthCardInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              monthCards_.add(
                  input.readMessage(com.protos.monthCard.MonthCard.MonthCardInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          monthCards_ = java.util.Collections.unmodifiableList(monthCards_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoACK_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoACK_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.monthCard.MonthCard.MonthCardInfoACK.class, com.protos.monthCard.MonthCard.MonthCardInfoACK.Builder.class);
    }

    public static final int MONTHCARDS_FIELD_NUMBER = 1;
    private java.util.List<com.protos.monthCard.MonthCard.MonthCardInfo> monthCards_;
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    public java.util.List<com.protos.monthCard.MonthCard.MonthCardInfo> getMonthCardsList() {
      return monthCards_;
    }
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    public java.util.List<? extends com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder> 
        getMonthCardsOrBuilderList() {
      return monthCards_;
    }
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    public int getMonthCardsCount() {
      return monthCards_.size();
    }
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    public com.protos.monthCard.MonthCard.MonthCardInfo getMonthCards(int index) {
      return monthCards_.get(index);
    }
    /**
     * <pre>
     *  多个月卡档领取信息
     * </pre>
     *
     * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
     */
    public com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder getMonthCardsOrBuilder(
        int index) {
      return monthCards_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < monthCards_.size(); i++) {
        output.writeMessage(1, monthCards_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < monthCards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, monthCards_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.monthCard.MonthCard.MonthCardInfoACK)) {
        return super.equals(obj);
      }
      com.protos.monthCard.MonthCard.MonthCardInfoACK other = (com.protos.monthCard.MonthCard.MonthCardInfoACK) obj;

      boolean result = true;
      result = result && getMonthCardsList()
          .equals(other.getMonthCardsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMonthCardsCount() > 0) {
        hash = (37 * hash) + MONTHCARDS_FIELD_NUMBER;
        hash = (53 * hash) + getMonthCardsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfoACK parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.monthCard.MonthCard.MonthCardInfoACK prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *月卡信息返回
     * </pre>
     *
     * Protobuf type {@code com.protos.monthCard.MonthCardInfoACK}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.monthCard.MonthCardInfoACK)
        com.protos.monthCard.MonthCard.MonthCardInfoACKOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoACK_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoACK_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.monthCard.MonthCard.MonthCardInfoACK.class, com.protos.monthCard.MonthCard.MonthCardInfoACK.Builder.class);
      }

      // Construct using com.protos.monthCard.MonthCard.MonthCardInfoACK.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMonthCardsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (monthCardsBuilder_ == null) {
          monthCards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          monthCardsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfoACK_descriptor;
      }

      public com.protos.monthCard.MonthCard.MonthCardInfoACK getDefaultInstanceForType() {
        return com.protos.monthCard.MonthCard.MonthCardInfoACK.getDefaultInstance();
      }

      public com.protos.monthCard.MonthCard.MonthCardInfoACK build() {
        com.protos.monthCard.MonthCard.MonthCardInfoACK result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.monthCard.MonthCard.MonthCardInfoACK buildPartial() {
        com.protos.monthCard.MonthCard.MonthCardInfoACK result = new com.protos.monthCard.MonthCard.MonthCardInfoACK(this);
        int from_bitField0_ = bitField0_;
        if (monthCardsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            monthCards_ = java.util.Collections.unmodifiableList(monthCards_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.monthCards_ = monthCards_;
        } else {
          result.monthCards_ = monthCardsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.monthCard.MonthCard.MonthCardInfoACK) {
          return mergeFrom((com.protos.monthCard.MonthCard.MonthCardInfoACK)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.monthCard.MonthCard.MonthCardInfoACK other) {
        if (other == com.protos.monthCard.MonthCard.MonthCardInfoACK.getDefaultInstance()) return this;
        if (monthCardsBuilder_ == null) {
          if (!other.monthCards_.isEmpty()) {
            if (monthCards_.isEmpty()) {
              monthCards_ = other.monthCards_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMonthCardsIsMutable();
              monthCards_.addAll(other.monthCards_);
            }
            onChanged();
          }
        } else {
          if (!other.monthCards_.isEmpty()) {
            if (monthCardsBuilder_.isEmpty()) {
              monthCardsBuilder_.dispose();
              monthCardsBuilder_ = null;
              monthCards_ = other.monthCards_;
              bitField0_ = (bitField0_ & ~0x00000001);
              monthCardsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMonthCardsFieldBuilder() : null;
            } else {
              monthCardsBuilder_.addAllMessages(other.monthCards_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.monthCard.MonthCard.MonthCardInfoACK parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.monthCard.MonthCard.MonthCardInfoACK) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.protos.monthCard.MonthCard.MonthCardInfo> monthCards_ =
        java.util.Collections.emptyList();
      private void ensureMonthCardsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          monthCards_ = new java.util.ArrayList<com.protos.monthCard.MonthCard.MonthCardInfo>(monthCards_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.monthCard.MonthCard.MonthCardInfo, com.protos.monthCard.MonthCard.MonthCardInfo.Builder, com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder> monthCardsBuilder_;

      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public java.util.List<com.protos.monthCard.MonthCard.MonthCardInfo> getMonthCardsList() {
        if (monthCardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(monthCards_);
        } else {
          return monthCardsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public int getMonthCardsCount() {
        if (monthCardsBuilder_ == null) {
          return monthCards_.size();
        } else {
          return monthCardsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public com.protos.monthCard.MonthCard.MonthCardInfo getMonthCards(int index) {
        if (monthCardsBuilder_ == null) {
          return monthCards_.get(index);
        } else {
          return monthCardsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder setMonthCards(
          int index, com.protos.monthCard.MonthCard.MonthCardInfo value) {
        if (monthCardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonthCardsIsMutable();
          monthCards_.set(index, value);
          onChanged();
        } else {
          monthCardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder setMonthCards(
          int index, com.protos.monthCard.MonthCard.MonthCardInfo.Builder builderForValue) {
        if (monthCardsBuilder_ == null) {
          ensureMonthCardsIsMutable();
          monthCards_.set(index, builderForValue.build());
          onChanged();
        } else {
          monthCardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder addMonthCards(com.protos.monthCard.MonthCard.MonthCardInfo value) {
        if (monthCardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonthCardsIsMutable();
          monthCards_.add(value);
          onChanged();
        } else {
          monthCardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder addMonthCards(
          int index, com.protos.monthCard.MonthCard.MonthCardInfo value) {
        if (monthCardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonthCardsIsMutable();
          monthCards_.add(index, value);
          onChanged();
        } else {
          monthCardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder addMonthCards(
          com.protos.monthCard.MonthCard.MonthCardInfo.Builder builderForValue) {
        if (monthCardsBuilder_ == null) {
          ensureMonthCardsIsMutable();
          monthCards_.add(builderForValue.build());
          onChanged();
        } else {
          monthCardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder addMonthCards(
          int index, com.protos.monthCard.MonthCard.MonthCardInfo.Builder builderForValue) {
        if (monthCardsBuilder_ == null) {
          ensureMonthCardsIsMutable();
          monthCards_.add(index, builderForValue.build());
          onChanged();
        } else {
          monthCardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder addAllMonthCards(
          java.lang.Iterable<? extends com.protos.monthCard.MonthCard.MonthCardInfo> values) {
        if (monthCardsBuilder_ == null) {
          ensureMonthCardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, monthCards_);
          onChanged();
        } else {
          monthCardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder clearMonthCards() {
        if (monthCardsBuilder_ == null) {
          monthCards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          monthCardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public Builder removeMonthCards(int index) {
        if (monthCardsBuilder_ == null) {
          ensureMonthCardsIsMutable();
          monthCards_.remove(index);
          onChanged();
        } else {
          monthCardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public com.protos.monthCard.MonthCard.MonthCardInfo.Builder getMonthCardsBuilder(
          int index) {
        return getMonthCardsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder getMonthCardsOrBuilder(
          int index) {
        if (monthCardsBuilder_ == null) {
          return monthCards_.get(index);  } else {
          return monthCardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public java.util.List<? extends com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder> 
           getMonthCardsOrBuilderList() {
        if (monthCardsBuilder_ != null) {
          return monthCardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(monthCards_);
        }
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public com.protos.monthCard.MonthCard.MonthCardInfo.Builder addMonthCardsBuilder() {
        return getMonthCardsFieldBuilder().addBuilder(
            com.protos.monthCard.MonthCard.MonthCardInfo.getDefaultInstance());
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public com.protos.monthCard.MonthCard.MonthCardInfo.Builder addMonthCardsBuilder(
          int index) {
        return getMonthCardsFieldBuilder().addBuilder(
            index, com.protos.monthCard.MonthCard.MonthCardInfo.getDefaultInstance());
      }
      /**
       * <pre>
       *  多个月卡档领取信息
       * </pre>
       *
       * <code>repeated .com.protos.monthCard.MonthCardInfo monthCards = 1;</code>
       */
      public java.util.List<com.protos.monthCard.MonthCard.MonthCardInfo.Builder> 
           getMonthCardsBuilderList() {
        return getMonthCardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.monthCard.MonthCard.MonthCardInfo, com.protos.monthCard.MonthCard.MonthCardInfo.Builder, com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder> 
          getMonthCardsFieldBuilder() {
        if (monthCardsBuilder_ == null) {
          monthCardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.protos.monthCard.MonthCard.MonthCardInfo, com.protos.monthCard.MonthCard.MonthCardInfo.Builder, com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder>(
                  monthCards_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          monthCards_ = null;
        }
        return monthCardsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.monthCard.MonthCardInfoACK)
    }

    // @@protoc_insertion_point(class_scope:com.protos.monthCard.MonthCardInfoACK)
    private static final com.protos.monthCard.MonthCard.MonthCardInfoACK DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.monthCard.MonthCard.MonthCardInfoACK();
    }

    public static com.protos.monthCard.MonthCard.MonthCardInfoACK getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonthCardInfoACK>
        PARSER = new com.google.protobuf.AbstractParser<MonthCardInfoACK>() {
      public MonthCardInfoACK parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MonthCardInfoACK(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonthCardInfoACK> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonthCardInfoACK> getParserForType() {
      return PARSER;
    }

    public com.protos.monthCard.MonthCard.MonthCardInfoACK getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetMonthCardDayGoldREQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.monthCard.GetMonthCardDayGoldREQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  月卡档id
     * </pre>
     *
     * <code>uint32 cardId = 1;</code>
     */
    int getCardId();
  }
  /**
   * <pre>
   *领取月卡每日贝壳
   * </pre>
   *
   * Protobuf type {@code com.protos.monthCard.GetMonthCardDayGoldREQ}
   */
  public  static final class GetMonthCardDayGoldREQ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.monthCard.GetMonthCardDayGoldREQ)
      GetMonthCardDayGoldREQOrBuilder {
    // Use GetMonthCardDayGoldREQ.newBuilder() to construct.
    private GetMonthCardDayGoldREQ(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetMonthCardDayGoldREQ() {
      cardId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetMonthCardDayGoldREQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cardId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ.class, com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ.Builder.class);
    }

    public static final int CARDID_FIELD_NUMBER = 1;
    private int cardId_;
    /**
     * <pre>
     *  月卡档id
     * </pre>
     *
     * <code>uint32 cardId = 1;</code>
     */
    public int getCardId() {
      return cardId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cardId_ != 0) {
        output.writeUInt32(1, cardId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cardId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, cardId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ)) {
        return super.equals(obj);
      }
      com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ other = (com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ) obj;

      boolean result = true;
      result = result && (getCardId()
          == other.getCardId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CARDID_FIELD_NUMBER;
      hash = (53 * hash) + getCardId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *领取月卡每日贝壳
     * </pre>
     *
     * Protobuf type {@code com.protos.monthCard.GetMonthCardDayGoldREQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.monthCard.GetMonthCardDayGoldREQ)
        com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ.class, com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ.Builder.class);
      }

      // Construct using com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cardId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_descriptor;
      }

      public com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ getDefaultInstanceForType() {
        return com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ.getDefaultInstance();
      }

      public com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ build() {
        com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ buildPartial() {
        com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ result = new com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ(this);
        result.cardId_ = cardId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ) {
          return mergeFrom((com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ other) {
        if (other == com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ.getDefaultInstance()) return this;
        if (other.getCardId() != 0) {
          setCardId(other.getCardId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cardId_ ;
      /**
       * <pre>
       *  月卡档id
       * </pre>
       *
       * <code>uint32 cardId = 1;</code>
       */
      public int getCardId() {
        return cardId_;
      }
      /**
       * <pre>
       *  月卡档id
       * </pre>
       *
       * <code>uint32 cardId = 1;</code>
       */
      public Builder setCardId(int value) {
        
        cardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  月卡档id
       * </pre>
       *
       * <code>uint32 cardId = 1;</code>
       */
      public Builder clearCardId() {
        
        cardId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.monthCard.GetMonthCardDayGoldREQ)
    }

    // @@protoc_insertion_point(class_scope:com.protos.monthCard.GetMonthCardDayGoldREQ)
    private static final com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ();
    }

    public static com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetMonthCardDayGoldREQ>
        PARSER = new com.google.protobuf.AbstractParser<GetMonthCardDayGoldREQ>() {
      public GetMonthCardDayGoldREQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetMonthCardDayGoldREQ(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetMonthCardDayGoldREQ> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetMonthCardDayGoldREQ> getParserForType() {
      return PARSER;
    }

    public com.protos.monthCard.MonthCard.GetMonthCardDayGoldREQ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MonthCardInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.monthCard.MonthCardInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  月卡档id
     * </pre>
     *
     * <code>uint32 cardId = 1;</code>
     */
    int getCardId();

    /**
     * <pre>
     * 0-不能领取, 1-可领取未领取, 2-已领取
     * </pre>
     *
     * <code>uint32 status = 2;</code>
     */
    int getStatus();

    /**
     * <pre>
     *剩余多少天到期
     * </pre>
     *
     * <code>uint32 expireTime = 3;</code>
     */
    int getExpireTime();
  }
  /**
   * <pre>
   *月卡档领取状态
   * </pre>
   *
   * Protobuf type {@code com.protos.monthCard.MonthCardInfo}
   */
  public  static final class MonthCardInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.monthCard.MonthCardInfo)
      MonthCardInfoOrBuilder {
    // Use MonthCardInfo.newBuilder() to construct.
    private MonthCardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonthCardInfo() {
      cardId_ = 0;
      status_ = 0;
      expireTime_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MonthCardInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cardId_ = input.readUInt32();
              break;
            }
            case 16: {

              status_ = input.readUInt32();
              break;
            }
            case 24: {

              expireTime_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.monthCard.MonthCard.MonthCardInfo.class, com.protos.monthCard.MonthCard.MonthCardInfo.Builder.class);
    }

    public static final int CARDID_FIELD_NUMBER = 1;
    private int cardId_;
    /**
     * <pre>
     *  月卡档id
     * </pre>
     *
     * <code>uint32 cardId = 1;</code>
     */
    public int getCardId() {
      return cardId_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <pre>
     * 0-不能领取, 1-可领取未领取, 2-已领取
     * </pre>
     *
     * <code>uint32 status = 2;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int EXPIRETIME_FIELD_NUMBER = 3;
    private int expireTime_;
    /**
     * <pre>
     *剩余多少天到期
     * </pre>
     *
     * <code>uint32 expireTime = 3;</code>
     */
    public int getExpireTime() {
      return expireTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cardId_ != 0) {
        output.writeUInt32(1, cardId_);
      }
      if (status_ != 0) {
        output.writeUInt32(2, status_);
      }
      if (expireTime_ != 0) {
        output.writeUInt32(3, expireTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cardId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, cardId_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, status_);
      }
      if (expireTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, expireTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.monthCard.MonthCard.MonthCardInfo)) {
        return super.equals(obj);
      }
      com.protos.monthCard.MonthCard.MonthCardInfo other = (com.protos.monthCard.MonthCard.MonthCardInfo) obj;

      boolean result = true;
      result = result && (getCardId()
          == other.getCardId());
      result = result && (getStatus()
          == other.getStatus());
      result = result && (getExpireTime()
          == other.getExpireTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CARDID_FIELD_NUMBER;
      hash = (53 * hash) + getCardId();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + EXPIRETIME_FIELD_NUMBER;
      hash = (53 * hash) + getExpireTime();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.monthCard.MonthCard.MonthCardInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.monthCard.MonthCard.MonthCardInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *月卡档领取状态
     * </pre>
     *
     * Protobuf type {@code com.protos.monthCard.MonthCardInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.monthCard.MonthCardInfo)
        com.protos.monthCard.MonthCard.MonthCardInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.monthCard.MonthCard.MonthCardInfo.class, com.protos.monthCard.MonthCard.MonthCardInfo.Builder.class);
      }

      // Construct using com.protos.monthCard.MonthCard.MonthCardInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cardId_ = 0;

        status_ = 0;

        expireTime_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.monthCard.MonthCard.internal_static_com_protos_monthCard_MonthCardInfo_descriptor;
      }

      public com.protos.monthCard.MonthCard.MonthCardInfo getDefaultInstanceForType() {
        return com.protos.monthCard.MonthCard.MonthCardInfo.getDefaultInstance();
      }

      public com.protos.monthCard.MonthCard.MonthCardInfo build() {
        com.protos.monthCard.MonthCard.MonthCardInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.monthCard.MonthCard.MonthCardInfo buildPartial() {
        com.protos.monthCard.MonthCard.MonthCardInfo result = new com.protos.monthCard.MonthCard.MonthCardInfo(this);
        result.cardId_ = cardId_;
        result.status_ = status_;
        result.expireTime_ = expireTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.monthCard.MonthCard.MonthCardInfo) {
          return mergeFrom((com.protos.monthCard.MonthCard.MonthCardInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.monthCard.MonthCard.MonthCardInfo other) {
        if (other == com.protos.monthCard.MonthCard.MonthCardInfo.getDefaultInstance()) return this;
        if (other.getCardId() != 0) {
          setCardId(other.getCardId());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getExpireTime() != 0) {
          setExpireTime(other.getExpireTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.monthCard.MonthCard.MonthCardInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.monthCard.MonthCard.MonthCardInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cardId_ ;
      /**
       * <pre>
       *  月卡档id
       * </pre>
       *
       * <code>uint32 cardId = 1;</code>
       */
      public int getCardId() {
        return cardId_;
      }
      /**
       * <pre>
       *  月卡档id
       * </pre>
       *
       * <code>uint32 cardId = 1;</code>
       */
      public Builder setCardId(int value) {
        
        cardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  月卡档id
       * </pre>
       *
       * <code>uint32 cardId = 1;</code>
       */
      public Builder clearCardId() {
        
        cardId_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 0-不能领取, 1-可领取未领取, 2-已领取
       * </pre>
       *
       * <code>uint32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 0-不能领取, 1-可领取未领取, 2-已领取
       * </pre>
       *
       * <code>uint32 status = 2;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0-不能领取, 1-可领取未领取, 2-已领取
       * </pre>
       *
       * <code>uint32 status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int expireTime_ ;
      /**
       * <pre>
       *剩余多少天到期
       * </pre>
       *
       * <code>uint32 expireTime = 3;</code>
       */
      public int getExpireTime() {
        return expireTime_;
      }
      /**
       * <pre>
       *剩余多少天到期
       * </pre>
       *
       * <code>uint32 expireTime = 3;</code>
       */
      public Builder setExpireTime(int value) {
        
        expireTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *剩余多少天到期
       * </pre>
       *
       * <code>uint32 expireTime = 3;</code>
       */
      public Builder clearExpireTime() {
        
        expireTime_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.monthCard.MonthCardInfo)
    }

    // @@protoc_insertion_point(class_scope:com.protos.monthCard.MonthCardInfo)
    private static final com.protos.monthCard.MonthCard.MonthCardInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.monthCard.MonthCard.MonthCardInfo();
    }

    public static com.protos.monthCard.MonthCard.MonthCardInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonthCardInfo>
        PARSER = new com.google.protobuf.AbstractParser<MonthCardInfo>() {
      public MonthCardInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MonthCardInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonthCardInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonthCardInfo> getParserForType() {
      return PARSER;
    }

    public com.protos.monthCard.MonthCard.MonthCardInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_monthCard_MonthCardInfoREQ_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_monthCard_MonthCardInfoREQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_monthCard_MonthCardInfoACK_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_monthCard_MonthCardInfoACK_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_monthCard_MonthCardInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_monthCard_MonthCardInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MonthCard.proto\022\024com.protos.monthCard\"" +
      "#\n\020MonthCardInfoREQ\022\017\n\007default\030\001 \001(\r\"K\n\020" +
      "MonthCardInfoACK\0227\n\nmonthCards\030\001 \003(\0132#.c" +
      "om.protos.monthCard.MonthCardInfo\"(\n\026Get" +
      "MonthCardDayGoldREQ\022\016\n\006cardId\030\001 \001(\r\"C\n\rM" +
      "onthCardInfo\022\016\n\006cardId\030\001 \001(\r\022\016\n\006status\030\002" +
      " \001(\r\022\022\n\nexpireTime\030\003 \001(\rb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protos_monthCard_MonthCardInfoREQ_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_monthCard_MonthCardInfoREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_monthCard_MonthCardInfoREQ_descriptor,
        new java.lang.String[] { "Default", });
    internal_static_com_protos_monthCard_MonthCardInfoACK_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protos_monthCard_MonthCardInfoACK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_monthCard_MonthCardInfoACK_descriptor,
        new java.lang.String[] { "MonthCards", });
    internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_monthCard_GetMonthCardDayGoldREQ_descriptor,
        new java.lang.String[] { "CardId", });
    internal_static_com_protos_monthCard_MonthCardInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_protos_monthCard_MonthCardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_monthCard_MonthCardInfo_descriptor,
        new java.lang.String[] { "CardId", "Status", "ExpireTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
