// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gradeFright.proto

package com.protos.gradeFright;

public final class GradeFright {
  private GradeFright() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GradeFrightInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.gradeFright.GradeFrightInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *模块id
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     *当前进度
     * </pre>
     *
     * <code>uint32 exp = 2;</code>
     */
    int getExp();

    /**
     * <pre>
     *最大进度
     * </pre>
     *
     * <code>uint32 maxExp = 3;</code>
     */
    int getMaxExp();
  }
  /**
   * <pre>
   *单个战力引导的信息
   * </pre>
   *
   * Protobuf type {@code com.protos.gradeFright.GradeFrightInfo}
   */
  public  static final class GradeFrightInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.gradeFright.GradeFrightInfo)
      GradeFrightInfoOrBuilder {
    // Use GradeFrightInfo.newBuilder() to construct.
    private GradeFrightInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GradeFrightInfo() {
      id_ = 0;
      exp_ = 0;
      maxExp_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GradeFrightInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 16: {

              exp_ = input.readUInt32();
              break;
            }
            case 24: {

              maxExp_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.gradeFright.GradeFright.GradeFrightInfo.class, com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *模块id
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EXP_FIELD_NUMBER = 2;
    private int exp_;
    /**
     * <pre>
     *当前进度
     * </pre>
     *
     * <code>uint32 exp = 2;</code>
     */
    public int getExp() {
      return exp_;
    }

    public static final int MAXEXP_FIELD_NUMBER = 3;
    private int maxExp_;
    /**
     * <pre>
     *最大进度
     * </pre>
     *
     * <code>uint32 maxExp = 3;</code>
     */
    public int getMaxExp() {
      return maxExp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (exp_ != 0) {
        output.writeUInt32(2, exp_);
      }
      if (maxExp_ != 0) {
        output.writeUInt32(3, maxExp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (exp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, exp_);
      }
      if (maxExp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, maxExp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.gradeFright.GradeFright.GradeFrightInfo)) {
        return super.equals(obj);
      }
      com.protos.gradeFright.GradeFright.GradeFrightInfo other = (com.protos.gradeFright.GradeFright.GradeFrightInfo) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getExp()
          == other.getExp());
      result = result && (getMaxExp()
          == other.getMaxExp());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EXP_FIELD_NUMBER;
      hash = (53 * hash) + getExp();
      hash = (37 * hash) + MAXEXP_FIELD_NUMBER;
      hash = (53 * hash) + getMaxExp();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.gradeFright.GradeFright.GradeFrightInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *单个战力引导的信息
     * </pre>
     *
     * Protobuf type {@code com.protos.gradeFright.GradeFrightInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.gradeFright.GradeFrightInfo)
        com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.gradeFright.GradeFright.GradeFrightInfo.class, com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder.class);
      }

      // Construct using com.protos.gradeFright.GradeFright.GradeFrightInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        exp_ = 0;

        maxExp_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfo_descriptor;
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfo getDefaultInstanceForType() {
        return com.protos.gradeFright.GradeFright.GradeFrightInfo.getDefaultInstance();
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfo build() {
        com.protos.gradeFright.GradeFright.GradeFrightInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfo buildPartial() {
        com.protos.gradeFright.GradeFright.GradeFrightInfo result = new com.protos.gradeFright.GradeFright.GradeFrightInfo(this);
        result.id_ = id_;
        result.exp_ = exp_;
        result.maxExp_ = maxExp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.gradeFright.GradeFright.GradeFrightInfo) {
          return mergeFrom((com.protos.gradeFright.GradeFright.GradeFrightInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.gradeFright.GradeFright.GradeFrightInfo other) {
        if (other == com.protos.gradeFright.GradeFright.GradeFrightInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getExp() != 0) {
          setExp(other.getExp());
        }
        if (other.getMaxExp() != 0) {
          setMaxExp(other.getMaxExp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.gradeFright.GradeFright.GradeFrightInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.gradeFright.GradeFright.GradeFrightInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       *模块id
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *模块id
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *模块id
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int exp_ ;
      /**
       * <pre>
       *当前进度
       * </pre>
       *
       * <code>uint32 exp = 2;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <pre>
       *当前进度
       * </pre>
       *
       * <code>uint32 exp = 2;</code>
       */
      public Builder setExp(int value) {
        
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前进度
       * </pre>
       *
       * <code>uint32 exp = 2;</code>
       */
      public Builder clearExp() {
        
        exp_ = 0;
        onChanged();
        return this;
      }

      private int maxExp_ ;
      /**
       * <pre>
       *最大进度
       * </pre>
       *
       * <code>uint32 maxExp = 3;</code>
       */
      public int getMaxExp() {
        return maxExp_;
      }
      /**
       * <pre>
       *最大进度
       * </pre>
       *
       * <code>uint32 maxExp = 3;</code>
       */
      public Builder setMaxExp(int value) {
        
        maxExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最大进度
       * </pre>
       *
       * <code>uint32 maxExp = 3;</code>
       */
      public Builder clearMaxExp() {
        
        maxExp_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.gradeFright.GradeFrightInfo)
    }

    // @@protoc_insertion_point(class_scope:com.protos.gradeFright.GradeFrightInfo)
    private static final com.protos.gradeFright.GradeFright.GradeFrightInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.gradeFright.GradeFright.GradeFrightInfo();
    }

    public static com.protos.gradeFright.GradeFright.GradeFrightInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GradeFrightInfo>
        PARSER = new com.google.protobuf.AbstractParser<GradeFrightInfo>() {
      public GradeFrightInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GradeFrightInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GradeFrightInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GradeFrightInfo> getParserForType() {
      return PARSER;
    }

    public com.protos.gradeFright.GradeFright.GradeFrightInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GradeFrightInfoREQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.gradeFright.GradeFrightInfoREQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1个人，2团队，3其它
     * </pre>
     *
     * <code>uint32 group = 1;</code>
     */
    int getGroup();

    /**
     * <pre>
     *标识
     * </pre>
     *
     * <code>uint64 heroId = 2;</code>
     */
    long getHeroId();

    /**
     * <pre>
     *1头相战力，2战斗失败
     * </pre>
     *
     * <code>uint32 type = 3;</code>
     */
    int getType();
  }
  /**
   * <pre>
   *战力引导的信息获取
   * </pre>
   *
   * Protobuf type {@code com.protos.gradeFright.GradeFrightInfoREQ}
   */
  public  static final class GradeFrightInfoREQ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.gradeFright.GradeFrightInfoREQ)
      GradeFrightInfoREQOrBuilder {
    // Use GradeFrightInfoREQ.newBuilder() to construct.
    private GradeFrightInfoREQ(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GradeFrightInfoREQ() {
      group_ = 0;
      heroId_ = 0L;
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GradeFrightInfoREQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              group_ = input.readUInt32();
              break;
            }
            case 16: {

              heroId_ = input.readUInt64();
              break;
            }
            case 24: {

              type_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoREQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoREQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.gradeFright.GradeFright.GradeFrightInfoREQ.class, com.protos.gradeFright.GradeFright.GradeFrightInfoREQ.Builder.class);
    }

    public static final int GROUP_FIELD_NUMBER = 1;
    private int group_;
    /**
     * <pre>
     *1个人，2团队，3其它
     * </pre>
     *
     * <code>uint32 group = 1;</code>
     */
    public int getGroup() {
      return group_;
    }

    public static final int HEROID_FIELD_NUMBER = 2;
    private long heroId_;
    /**
     * <pre>
     *标识
     * </pre>
     *
     * <code>uint64 heroId = 2;</code>
     */
    public long getHeroId() {
      return heroId_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     *1头相战力，2战斗失败
     * </pre>
     *
     * <code>uint32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (group_ != 0) {
        output.writeUInt32(1, group_);
      }
      if (heroId_ != 0L) {
        output.writeUInt64(2, heroId_);
      }
      if (type_ != 0) {
        output.writeUInt32(3, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (group_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, group_);
      }
      if (heroId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, heroId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.gradeFright.GradeFright.GradeFrightInfoREQ)) {
        return super.equals(obj);
      }
      com.protos.gradeFright.GradeFright.GradeFrightInfoREQ other = (com.protos.gradeFright.GradeFright.GradeFrightInfoREQ) obj;

      boolean result = true;
      result = result && (getGroup()
          == other.getGroup());
      result = result && (getHeroId()
          == other.getHeroId());
      result = result && (getType()
          == other.getType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup();
      hash = (37 * hash) + HEROID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeroId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.gradeFright.GradeFright.GradeFrightInfoREQ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *战力引导的信息获取
     * </pre>
     *
     * Protobuf type {@code com.protos.gradeFright.GradeFrightInfoREQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.gradeFright.GradeFrightInfoREQ)
        com.protos.gradeFright.GradeFright.GradeFrightInfoREQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoREQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoREQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.gradeFright.GradeFright.GradeFrightInfoREQ.class, com.protos.gradeFright.GradeFright.GradeFrightInfoREQ.Builder.class);
      }

      // Construct using com.protos.gradeFright.GradeFright.GradeFrightInfoREQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        group_ = 0;

        heroId_ = 0L;

        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoREQ_descriptor;
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfoREQ getDefaultInstanceForType() {
        return com.protos.gradeFright.GradeFright.GradeFrightInfoREQ.getDefaultInstance();
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfoREQ build() {
        com.protos.gradeFright.GradeFright.GradeFrightInfoREQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfoREQ buildPartial() {
        com.protos.gradeFright.GradeFright.GradeFrightInfoREQ result = new com.protos.gradeFright.GradeFright.GradeFrightInfoREQ(this);
        result.group_ = group_;
        result.heroId_ = heroId_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.gradeFright.GradeFright.GradeFrightInfoREQ) {
          return mergeFrom((com.protos.gradeFright.GradeFright.GradeFrightInfoREQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.gradeFright.GradeFright.GradeFrightInfoREQ other) {
        if (other == com.protos.gradeFright.GradeFright.GradeFrightInfoREQ.getDefaultInstance()) return this;
        if (other.getGroup() != 0) {
          setGroup(other.getGroup());
        }
        if (other.getHeroId() != 0L) {
          setHeroId(other.getHeroId());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.gradeFright.GradeFright.GradeFrightInfoREQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.gradeFright.GradeFright.GradeFrightInfoREQ) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int group_ ;
      /**
       * <pre>
       *1个人，2团队，3其它
       * </pre>
       *
       * <code>uint32 group = 1;</code>
       */
      public int getGroup() {
        return group_;
      }
      /**
       * <pre>
       *1个人，2团队，3其它
       * </pre>
       *
       * <code>uint32 group = 1;</code>
       */
      public Builder setGroup(int value) {
        
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1个人，2团队，3其它
       * </pre>
       *
       * <code>uint32 group = 1;</code>
       */
      public Builder clearGroup() {
        
        group_ = 0;
        onChanged();
        return this;
      }

      private long heroId_ ;
      /**
       * <pre>
       *标识
       * </pre>
       *
       * <code>uint64 heroId = 2;</code>
       */
      public long getHeroId() {
        return heroId_;
      }
      /**
       * <pre>
       *标识
       * </pre>
       *
       * <code>uint64 heroId = 2;</code>
       */
      public Builder setHeroId(long value) {
        
        heroId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *标识
       * </pre>
       *
       * <code>uint64 heroId = 2;</code>
       */
      public Builder clearHeroId() {
        
        heroId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *1头相战力，2战斗失败
       * </pre>
       *
       * <code>uint32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *1头相战力，2战斗失败
       * </pre>
       *
       * <code>uint32 type = 3;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1头相战力，2战斗失败
       * </pre>
       *
       * <code>uint32 type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.gradeFright.GradeFrightInfoREQ)
    }

    // @@protoc_insertion_point(class_scope:com.protos.gradeFright.GradeFrightInfoREQ)
    private static final com.protos.gradeFright.GradeFright.GradeFrightInfoREQ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.gradeFright.GradeFright.GradeFrightInfoREQ();
    }

    public static com.protos.gradeFright.GradeFright.GradeFrightInfoREQ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GradeFrightInfoREQ>
        PARSER = new com.google.protobuf.AbstractParser<GradeFrightInfoREQ>() {
      public GradeFrightInfoREQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GradeFrightInfoREQ(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GradeFrightInfoREQ> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GradeFrightInfoREQ> getParserForType() {
      return PARSER;
    }

    public com.protos.gradeFright.GradeFright.GradeFrightInfoREQ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GradeFrightInfoACKOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.gradeFright.GradeFrightInfoACK)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *标识
     * </pre>
     *
     * <code>uint64 heroId = 1;</code>
     */
    long getHeroId();

    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    java.util.List<com.protos.gradeFright.GradeFright.GradeFrightInfo> 
        getInfosList();
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    com.protos.gradeFright.GradeFright.GradeFrightInfo getInfos(int index);
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    java.util.List<? extends com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder> 
        getInfosOrBuilderList();
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder getInfosOrBuilder(
        int index);

    /**
     * <pre>
     *1头相战力，2战斗失败
     * </pre>
     *
     * <code>uint32 type = 3;</code>
     */
    int getType();
  }
  /**
   * <pre>
   *战力引导的信息获取返回
   * </pre>
   *
   * Protobuf type {@code com.protos.gradeFright.GradeFrightInfoACK}
   */
  public  static final class GradeFrightInfoACK extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.gradeFright.GradeFrightInfoACK)
      GradeFrightInfoACKOrBuilder {
    // Use GradeFrightInfoACK.newBuilder() to construct.
    private GradeFrightInfoACK(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GradeFrightInfoACK() {
      heroId_ = 0L;
      infos_ = java.util.Collections.emptyList();
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GradeFrightInfoACK(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              heroId_ = input.readUInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                infos_ = new java.util.ArrayList<com.protos.gradeFright.GradeFright.GradeFrightInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              infos_.add(
                  input.readMessage(com.protos.gradeFright.GradeFright.GradeFrightInfo.parser(), extensionRegistry));
              break;
            }
            case 24: {

              type_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoACK_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoACK_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.gradeFright.GradeFright.GradeFrightInfoACK.class, com.protos.gradeFright.GradeFright.GradeFrightInfoACK.Builder.class);
    }

    private int bitField0_;
    public static final int HEROID_FIELD_NUMBER = 1;
    private long heroId_;
    /**
     * <pre>
     *标识
     * </pre>
     *
     * <code>uint64 heroId = 1;</code>
     */
    public long getHeroId() {
      return heroId_;
    }

    public static final int INFOS_FIELD_NUMBER = 2;
    private java.util.List<com.protos.gradeFright.GradeFright.GradeFrightInfo> infos_;
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    public java.util.List<com.protos.gradeFright.GradeFright.GradeFrightInfo> getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    public java.util.List<? extends com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder> 
        getInfosOrBuilderList() {
      return infos_;
    }
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    public com.protos.gradeFright.GradeFright.GradeFrightInfo getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
     */
    public com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder getInfosOrBuilder(
        int index) {
      return infos_.get(index);
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     *1头相战力，2战斗失败
     * </pre>
     *
     * <code>uint32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (heroId_ != 0L) {
        output.writeUInt64(1, heroId_);
      }
      for (int i = 0; i < infos_.size(); i++) {
        output.writeMessage(2, infos_.get(i));
      }
      if (type_ != 0) {
        output.writeUInt32(3, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (heroId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, heroId_);
      }
      for (int i = 0; i < infos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, infos_.get(i));
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.gradeFright.GradeFright.GradeFrightInfoACK)) {
        return super.equals(obj);
      }
      com.protos.gradeFright.GradeFright.GradeFrightInfoACK other = (com.protos.gradeFright.GradeFright.GradeFrightInfoACK) obj;

      boolean result = true;
      result = result && (getHeroId()
          == other.getHeroId());
      result = result && getInfosList()
          .equals(other.getInfosList());
      result = result && (getType()
          == other.getType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEROID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeroId());
      if (getInfosCount() > 0) {
        hash = (37 * hash) + INFOS_FIELD_NUMBER;
        hash = (53 * hash) + getInfosList().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.gradeFright.GradeFright.GradeFrightInfoACK prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *战力引导的信息获取返回
     * </pre>
     *
     * Protobuf type {@code com.protos.gradeFright.GradeFrightInfoACK}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.gradeFright.GradeFrightInfoACK)
        com.protos.gradeFright.GradeFright.GradeFrightInfoACKOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoACK_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoACK_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.gradeFright.GradeFright.GradeFrightInfoACK.class, com.protos.gradeFright.GradeFright.GradeFrightInfoACK.Builder.class);
      }

      // Construct using com.protos.gradeFright.GradeFright.GradeFrightInfoACK.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInfosFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        heroId_ = 0L;

        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          infosBuilder_.clear();
        }
        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.gradeFright.GradeFright.internal_static_com_protos_gradeFright_GradeFrightInfoACK_descriptor;
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfoACK getDefaultInstanceForType() {
        return com.protos.gradeFright.GradeFright.GradeFrightInfoACK.getDefaultInstance();
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfoACK build() {
        com.protos.gradeFright.GradeFright.GradeFrightInfoACK result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.gradeFright.GradeFright.GradeFrightInfoACK buildPartial() {
        com.protos.gradeFright.GradeFright.GradeFrightInfoACK result = new com.protos.gradeFright.GradeFright.GradeFrightInfoACK(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.heroId_ = heroId_;
        if (infosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            infos_ = java.util.Collections.unmodifiableList(infos_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.infos_ = infos_;
        } else {
          result.infos_ = infosBuilder_.build();
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.gradeFright.GradeFright.GradeFrightInfoACK) {
          return mergeFrom((com.protos.gradeFright.GradeFright.GradeFrightInfoACK)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.gradeFright.GradeFright.GradeFrightInfoACK other) {
        if (other == com.protos.gradeFright.GradeFright.GradeFrightInfoACK.getDefaultInstance()) return this;
        if (other.getHeroId() != 0L) {
          setHeroId(other.getHeroId());
        }
        if (infosBuilder_ == null) {
          if (!other.infos_.isEmpty()) {
            if (infos_.isEmpty()) {
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInfosIsMutable();
              infos_.addAll(other.infos_);
            }
            onChanged();
          }
        } else {
          if (!other.infos_.isEmpty()) {
            if (infosBuilder_.isEmpty()) {
              infosBuilder_.dispose();
              infosBuilder_ = null;
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000002);
              infosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInfosFieldBuilder() : null;
            } else {
              infosBuilder_.addAllMessages(other.infos_);
            }
          }
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.gradeFright.GradeFright.GradeFrightInfoACK parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.gradeFright.GradeFright.GradeFrightInfoACK) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long heroId_ ;
      /**
       * <pre>
       *标识
       * </pre>
       *
       * <code>uint64 heroId = 1;</code>
       */
      public long getHeroId() {
        return heroId_;
      }
      /**
       * <pre>
       *标识
       * </pre>
       *
       * <code>uint64 heroId = 1;</code>
       */
      public Builder setHeroId(long value) {
        
        heroId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *标识
       * </pre>
       *
       * <code>uint64 heroId = 1;</code>
       */
      public Builder clearHeroId() {
        
        heroId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.protos.gradeFright.GradeFright.GradeFrightInfo> infos_ =
        java.util.Collections.emptyList();
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          infos_ = new java.util.ArrayList<com.protos.gradeFright.GradeFright.GradeFrightInfo>(infos_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.gradeFright.GradeFright.GradeFrightInfo, com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder, com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder> infosBuilder_;

      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public java.util.List<com.protos.gradeFright.GradeFright.GradeFrightInfo> getInfosList() {
        if (infosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(infos_);
        } else {
          return infosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public int getInfosCount() {
        if (infosBuilder_ == null) {
          return infos_.size();
        } else {
          return infosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public com.protos.gradeFright.GradeFright.GradeFrightInfo getInfos(int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);
        } else {
          return infosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder setInfos(
          int index, com.protos.gradeFright.GradeFright.GradeFrightInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.set(index, value);
          onChanged();
        } else {
          infosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder setInfos(
          int index, com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.set(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder addInfos(com.protos.gradeFright.GradeFright.GradeFrightInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(value);
          onChanged();
        } else {
          infosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder addInfos(
          int index, com.protos.gradeFright.GradeFright.GradeFrightInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(index, value);
          onChanged();
        } else {
          infosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder addInfos(
          com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder addInfos(
          int index, com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<? extends com.protos.gradeFright.GradeFright.GradeFrightInfo> values) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, infos_);
          onChanged();
        } else {
          infosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder clearInfos() {
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          infosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public Builder removeInfos(int index) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.remove(index);
          onChanged();
        } else {
          infosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder getInfosBuilder(
          int index) {
        return getInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder getInfosOrBuilder(
          int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);  } else {
          return infosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public java.util.List<? extends com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder> 
           getInfosOrBuilderList() {
        if (infosBuilder_ != null) {
          return infosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(infos_);
        }
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder addInfosBuilder() {
        return getInfosFieldBuilder().addBuilder(
            com.protos.gradeFright.GradeFright.GradeFrightInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder addInfosBuilder(
          int index) {
        return getInfosFieldBuilder().addBuilder(
            index, com.protos.gradeFright.GradeFright.GradeFrightInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.gradeFright.GradeFrightInfo infos = 2;</code>
       */
      public java.util.List<com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder> 
           getInfosBuilderList() {
        return getInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.gradeFright.GradeFright.GradeFrightInfo, com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder, com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder> 
          getInfosFieldBuilder() {
        if (infosBuilder_ == null) {
          infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.protos.gradeFright.GradeFright.GradeFrightInfo, com.protos.gradeFright.GradeFright.GradeFrightInfo.Builder, com.protos.gradeFright.GradeFright.GradeFrightInfoOrBuilder>(
                  infos_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          infos_ = null;
        }
        return infosBuilder_;
      }

      private int type_ ;
      /**
       * <pre>
       *1头相战力，2战斗失败
       * </pre>
       *
       * <code>uint32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *1头相战力，2战斗失败
       * </pre>
       *
       * <code>uint32 type = 3;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1头相战力，2战斗失败
       * </pre>
       *
       * <code>uint32 type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.gradeFright.GradeFrightInfoACK)
    }

    // @@protoc_insertion_point(class_scope:com.protos.gradeFright.GradeFrightInfoACK)
    private static final com.protos.gradeFright.GradeFright.GradeFrightInfoACK DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.gradeFright.GradeFright.GradeFrightInfoACK();
    }

    public static com.protos.gradeFright.GradeFright.GradeFrightInfoACK getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GradeFrightInfoACK>
        PARSER = new com.google.protobuf.AbstractParser<GradeFrightInfoACK>() {
      public GradeFrightInfoACK parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GradeFrightInfoACK(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GradeFrightInfoACK> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GradeFrightInfoACK> getParserForType() {
      return PARSER;
    }

    public com.protos.gradeFright.GradeFright.GradeFrightInfoACK getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_gradeFright_GradeFrightInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_gradeFright_GradeFrightInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_gradeFright_GradeFrightInfoREQ_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_gradeFright_GradeFrightInfoREQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_gradeFright_GradeFrightInfoACK_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_gradeFright_GradeFrightInfoACK_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gradeFright.proto\022\026com.protos.gradeFri" +
      "ght\":\n\017GradeFrightInfo\022\n\n\002id\030\001 \001(\r\022\013\n\003ex" +
      "p\030\002 \001(\r\022\016\n\006maxExp\030\003 \001(\r\"A\n\022GradeFrightIn" +
      "foREQ\022\r\n\005group\030\001 \001(\r\022\016\n\006heroId\030\002 \001(\004\022\014\n\004" +
      "type\030\003 \001(\r\"j\n\022GradeFrightInfoACK\022\016\n\006hero" +
      "Id\030\001 \001(\004\0226\n\005infos\030\002 \003(\0132\'.com.protos.gra" +
      "deFright.GradeFrightInfo\022\014\n\004type\030\003 \001(\rb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protos_gradeFright_GradeFrightInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_gradeFright_GradeFrightInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_gradeFright_GradeFrightInfo_descriptor,
        new java.lang.String[] { "Id", "Exp", "MaxExp", });
    internal_static_com_protos_gradeFright_GradeFrightInfoREQ_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protos_gradeFright_GradeFrightInfoREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_gradeFright_GradeFrightInfoREQ_descriptor,
        new java.lang.String[] { "Group", "HeroId", "Type", });
    internal_static_com_protos_gradeFright_GradeFrightInfoACK_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_protos_gradeFright_GradeFrightInfoACK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_gradeFright_GradeFrightInfoACK_descriptor,
        new java.lang.String[] { "HeroId", "Infos", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
