// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.protos.account;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InitSocketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.account.InitSocket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>uint32 LType = 1;</code>
     */
    int getLType();
  }
  /**
   * Protobuf type {@code com.protos.account.InitSocket}
   */
  public  static final class InitSocket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.account.InitSocket)
      InitSocketOrBuilder {
    // Use InitSocket.newBuilder() to construct.
    private InitSocket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InitSocket() {
      lType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InitSocket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              lType_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.account.Account.internal_static_com_protos_account_InitSocket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.account.Account.internal_static_com_protos_account_InitSocket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.account.Account.InitSocket.class, com.protos.account.Account.InitSocket.Builder.class);
    }

    public static final int LTYPE_FIELD_NUMBER = 1;
    private int lType_;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>uint32 LType = 1;</code>
     */
    public int getLType() {
      return lType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lType_ != 0) {
        output.writeUInt32(1, lType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, lType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.account.Account.InitSocket)) {
        return super.equals(obj);
      }
      com.protos.account.Account.InitSocket other = (com.protos.account.Account.InitSocket) obj;

      boolean result = true;
      result = result && (getLType()
          == other.getLType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.account.Account.InitSocket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.InitSocket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.InitSocket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.InitSocket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.InitSocket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.InitSocket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.InitSocket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.InitSocket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.account.Account.InitSocket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.InitSocket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.account.Account.InitSocket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.InitSocket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.account.Account.InitSocket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.account.InitSocket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.account.InitSocket)
        com.protos.account.Account.InitSocketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.account.Account.internal_static_com_protos_account_InitSocket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.account.Account.internal_static_com_protos_account_InitSocket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.account.Account.InitSocket.class, com.protos.account.Account.InitSocket.Builder.class);
      }

      // Construct using com.protos.account.Account.InitSocket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        lType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.account.Account.internal_static_com_protos_account_InitSocket_descriptor;
      }

      public com.protos.account.Account.InitSocket getDefaultInstanceForType() {
        return com.protos.account.Account.InitSocket.getDefaultInstance();
      }

      public com.protos.account.Account.InitSocket build() {
        com.protos.account.Account.InitSocket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.account.Account.InitSocket buildPartial() {
        com.protos.account.Account.InitSocket result = new com.protos.account.Account.InitSocket(this);
        result.lType_ = lType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.account.Account.InitSocket) {
          return mergeFrom((com.protos.account.Account.InitSocket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.account.Account.InitSocket other) {
        if (other == com.protos.account.Account.InitSocket.getDefaultInstance()) return this;
        if (other.getLType() != 0) {
          setLType(other.getLType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.account.Account.InitSocket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.account.Account.InitSocket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int lType_ ;
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>uint32 LType = 1;</code>
       */
      public int getLType() {
        return lType_;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>uint32 LType = 1;</code>
       */
      public Builder setLType(int value) {
        
        lType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>uint32 LType = 1;</code>
       */
      public Builder clearLType() {
        
        lType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.account.InitSocket)
    }

    // @@protoc_insertion_point(class_scope:com.protos.account.InitSocket)
    private static final com.protos.account.Account.InitSocket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.account.Account.InitSocket();
    }

    public static com.protos.account.Account.InitSocket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InitSocket>
        PARSER = new com.google.protobuf.AbstractParser<InitSocket>() {
      public InitSocket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InitSocket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InitSocket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InitSocket> getParserForType() {
      return PARSER;
    }

    public com.protos.account.Account.InitSocket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginGameREQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.account.LoginGameREQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Cdkey = 1;</code>
     */
    java.lang.String getCdkey();
    /**
     * <code>string Cdkey = 1;</code>
     */
    com.google.protobuf.ByteString
        getCdkeyBytes();

    /**
     * <code>uint32 ServerID = 2;</code>
     */
    int getServerID();

    /**
     * <code>uint32 LType = 3;</code>
     */
    int getLType();
  }
  /**
   * <pre>
   *进入游戏
   * </pre>
   *
   * Protobuf type {@code com.protos.account.LoginGameREQ}
   */
  public  static final class LoginGameREQ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.account.LoginGameREQ)
      LoginGameREQOrBuilder {
    // Use LoginGameREQ.newBuilder() to construct.
    private LoginGameREQ(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginGameREQ() {
      cdkey_ = "";
      serverID_ = 0;
      lType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginGameREQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cdkey_ = s;
              break;
            }
            case 16: {

              serverID_ = input.readUInt32();
              break;
            }
            case 24: {

              lType_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.account.Account.internal_static_com_protos_account_LoginGameREQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.account.Account.internal_static_com_protos_account_LoginGameREQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.account.Account.LoginGameREQ.class, com.protos.account.Account.LoginGameREQ.Builder.class);
    }

    public static final int CDKEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object cdkey_;
    /**
     * <code>string Cdkey = 1;</code>
     */
    public java.lang.String getCdkey() {
      java.lang.Object ref = cdkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cdkey_ = s;
        return s;
      }
    }
    /**
     * <code>string Cdkey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCdkeyBytes() {
      java.lang.Object ref = cdkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cdkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERID_FIELD_NUMBER = 2;
    private int serverID_;
    /**
     * <code>uint32 ServerID = 2;</code>
     */
    public int getServerID() {
      return serverID_;
    }

    public static final int LTYPE_FIELD_NUMBER = 3;
    private int lType_;
    /**
     * <code>uint32 LType = 3;</code>
     */
    public int getLType() {
      return lType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCdkeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cdkey_);
      }
      if (serverID_ != 0) {
        output.writeUInt32(2, serverID_);
      }
      if (lType_ != 0) {
        output.writeUInt32(3, lType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCdkeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cdkey_);
      }
      if (serverID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, serverID_);
      }
      if (lType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, lType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.account.Account.LoginGameREQ)) {
        return super.equals(obj);
      }
      com.protos.account.Account.LoginGameREQ other = (com.protos.account.Account.LoginGameREQ) obj;

      boolean result = true;
      result = result && getCdkey()
          .equals(other.getCdkey());
      result = result && (getServerID()
          == other.getServerID());
      result = result && (getLType()
          == other.getLType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CDKEY_FIELD_NUMBER;
      hash = (53 * hash) + getCdkey().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerID();
      hash = (37 * hash) + LTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.account.Account.LoginGameREQ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameREQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.LoginGameREQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.LoginGameREQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.account.Account.LoginGameREQ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *进入游戏
     * </pre>
     *
     * Protobuf type {@code com.protos.account.LoginGameREQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.account.LoginGameREQ)
        com.protos.account.Account.LoginGameREQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.account.Account.internal_static_com_protos_account_LoginGameREQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.account.Account.internal_static_com_protos_account_LoginGameREQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.account.Account.LoginGameREQ.class, com.protos.account.Account.LoginGameREQ.Builder.class);
      }

      // Construct using com.protos.account.Account.LoginGameREQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cdkey_ = "";

        serverID_ = 0;

        lType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.account.Account.internal_static_com_protos_account_LoginGameREQ_descriptor;
      }

      public com.protos.account.Account.LoginGameREQ getDefaultInstanceForType() {
        return com.protos.account.Account.LoginGameREQ.getDefaultInstance();
      }

      public com.protos.account.Account.LoginGameREQ build() {
        com.protos.account.Account.LoginGameREQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.account.Account.LoginGameREQ buildPartial() {
        com.protos.account.Account.LoginGameREQ result = new com.protos.account.Account.LoginGameREQ(this);
        result.cdkey_ = cdkey_;
        result.serverID_ = serverID_;
        result.lType_ = lType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.account.Account.LoginGameREQ) {
          return mergeFrom((com.protos.account.Account.LoginGameREQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.account.Account.LoginGameREQ other) {
        if (other == com.protos.account.Account.LoginGameREQ.getDefaultInstance()) return this;
        if (!other.getCdkey().isEmpty()) {
          cdkey_ = other.cdkey_;
          onChanged();
        }
        if (other.getServerID() != 0) {
          setServerID(other.getServerID());
        }
        if (other.getLType() != 0) {
          setLType(other.getLType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.account.Account.LoginGameREQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.account.Account.LoginGameREQ) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object cdkey_ = "";
      /**
       * <code>string Cdkey = 1;</code>
       */
      public java.lang.String getCdkey() {
        java.lang.Object ref = cdkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cdkey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Cdkey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCdkeyBytes() {
        java.lang.Object ref = cdkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cdkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Cdkey = 1;</code>
       */
      public Builder setCdkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cdkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Cdkey = 1;</code>
       */
      public Builder clearCdkey() {
        
        cdkey_ = getDefaultInstance().getCdkey();
        onChanged();
        return this;
      }
      /**
       * <code>string Cdkey = 1;</code>
       */
      public Builder setCdkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cdkey_ = value;
        onChanged();
        return this;
      }

      private int serverID_ ;
      /**
       * <code>uint32 ServerID = 2;</code>
       */
      public int getServerID() {
        return serverID_;
      }
      /**
       * <code>uint32 ServerID = 2;</code>
       */
      public Builder setServerID(int value) {
        
        serverID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ServerID = 2;</code>
       */
      public Builder clearServerID() {
        
        serverID_ = 0;
        onChanged();
        return this;
      }

      private int lType_ ;
      /**
       * <code>uint32 LType = 3;</code>
       */
      public int getLType() {
        return lType_;
      }
      /**
       * <code>uint32 LType = 3;</code>
       */
      public Builder setLType(int value) {
        
        lType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 LType = 3;</code>
       */
      public Builder clearLType() {
        
        lType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.account.LoginGameREQ)
    }

    // @@protoc_insertion_point(class_scope:com.protos.account.LoginGameREQ)
    private static final com.protos.account.Account.LoginGameREQ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.account.Account.LoginGameREQ();
    }

    public static com.protos.account.Account.LoginGameREQ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginGameREQ>
        PARSER = new com.google.protobuf.AbstractParser<LoginGameREQ>() {
      public LoginGameREQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginGameREQ(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginGameREQ> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGameREQ> getParserForType() {
      return PARSER;
    }

    public com.protos.account.Account.LoginGameREQ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginGameACKOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.account.LoginGameACK)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 ServerID = 1;</code>
     */
    int getServerID();

    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    java.util.List<com.protos.player.Player.LoginPlayerInfo> 
        getPlayersList();
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    com.protos.player.Player.LoginPlayerInfo getPlayers(int index);
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    int getPlayersCount();
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    java.util.List<? extends com.protos.player.Player.LoginPlayerInfoOrBuilder> 
        getPlayersOrBuilderList();
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    com.protos.player.Player.LoginPlayerInfoOrBuilder getPlayersOrBuilder(
        int index);
  }
  /**
   * <pre>
   *进入游戏返回
   * </pre>
   *
   * Protobuf type {@code com.protos.account.LoginGameACK}
   */
  public  static final class LoginGameACK extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.account.LoginGameACK)
      LoginGameACKOrBuilder {
    // Use LoginGameACK.newBuilder() to construct.
    private LoginGameACK(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginGameACK() {
      serverID_ = 0;
      players_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginGameACK(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              serverID_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                players_ = new java.util.ArrayList<com.protos.player.Player.LoginPlayerInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              players_.add(
                  input.readMessage(com.protos.player.Player.LoginPlayerInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          players_ = java.util.Collections.unmodifiableList(players_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.account.Account.internal_static_com_protos_account_LoginGameACK_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.account.Account.internal_static_com_protos_account_LoginGameACK_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.account.Account.LoginGameACK.class, com.protos.account.Account.LoginGameACK.Builder.class);
    }

    private int bitField0_;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverID_;
    /**
     * <code>uint32 ServerID = 1;</code>
     */
    public int getServerID() {
      return serverID_;
    }

    public static final int PLAYERS_FIELD_NUMBER = 2;
    private java.util.List<com.protos.player.Player.LoginPlayerInfo> players_;
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    public java.util.List<com.protos.player.Player.LoginPlayerInfo> getPlayersList() {
      return players_;
    }
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    public java.util.List<? extends com.protos.player.Player.LoginPlayerInfoOrBuilder> 
        getPlayersOrBuilderList() {
      return players_;
    }
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    public int getPlayersCount() {
      return players_.size();
    }
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    public com.protos.player.Player.LoginPlayerInfo getPlayers(int index) {
      return players_.get(index);
    }
    /**
     * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
     */
    public com.protos.player.Player.LoginPlayerInfoOrBuilder getPlayersOrBuilder(
        int index) {
      return players_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverID_ != 0) {
        output.writeUInt32(1, serverID_);
      }
      for (int i = 0; i < players_.size(); i++) {
        output.writeMessage(2, players_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverID_);
      }
      for (int i = 0; i < players_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, players_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.account.Account.LoginGameACK)) {
        return super.equals(obj);
      }
      com.protos.account.Account.LoginGameACK other = (com.protos.account.Account.LoginGameACK) obj;

      boolean result = true;
      result = result && (getServerID()
          == other.getServerID());
      result = result && getPlayersList()
          .equals(other.getPlayersList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerID();
      if (getPlayersCount() > 0) {
        hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getPlayersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.account.Account.LoginGameACK parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameACK parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.LoginGameACK parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.LoginGameACK parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.account.Account.LoginGameACK prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *进入游戏返回
     * </pre>
     *
     * Protobuf type {@code com.protos.account.LoginGameACK}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.account.LoginGameACK)
        com.protos.account.Account.LoginGameACKOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.account.Account.internal_static_com_protos_account_LoginGameACK_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.account.Account.internal_static_com_protos_account_LoginGameACK_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.account.Account.LoginGameACK.class, com.protos.account.Account.LoginGameACK.Builder.class);
      }

      // Construct using com.protos.account.Account.LoginGameACK.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        serverID_ = 0;

        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          playersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.account.Account.internal_static_com_protos_account_LoginGameACK_descriptor;
      }

      public com.protos.account.Account.LoginGameACK getDefaultInstanceForType() {
        return com.protos.account.Account.LoginGameACK.getDefaultInstance();
      }

      public com.protos.account.Account.LoginGameACK build() {
        com.protos.account.Account.LoginGameACK result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.account.Account.LoginGameACK buildPartial() {
        com.protos.account.Account.LoginGameACK result = new com.protos.account.Account.LoginGameACK(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.serverID_ = serverID_;
        if (playersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            players_ = java.util.Collections.unmodifiableList(players_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.players_ = players_;
        } else {
          result.players_ = playersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.account.Account.LoginGameACK) {
          return mergeFrom((com.protos.account.Account.LoginGameACK)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.account.Account.LoginGameACK other) {
        if (other == com.protos.account.Account.LoginGameACK.getDefaultInstance()) return this;
        if (other.getServerID() != 0) {
          setServerID(other.getServerID());
        }
        if (playersBuilder_ == null) {
          if (!other.players_.isEmpty()) {
            if (players_.isEmpty()) {
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePlayersIsMutable();
              players_.addAll(other.players_);
            }
            onChanged();
          }
        } else {
          if (!other.players_.isEmpty()) {
            if (playersBuilder_.isEmpty()) {
              playersBuilder_.dispose();
              playersBuilder_ = null;
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
              playersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlayersFieldBuilder() : null;
            } else {
              playersBuilder_.addAllMessages(other.players_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.account.Account.LoginGameACK parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.account.Account.LoginGameACK) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverID_ ;
      /**
       * <code>uint32 ServerID = 1;</code>
       */
      public int getServerID() {
        return serverID_;
      }
      /**
       * <code>uint32 ServerID = 1;</code>
       */
      public Builder setServerID(int value) {
        
        serverID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ServerID = 1;</code>
       */
      public Builder clearServerID() {
        
        serverID_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.protos.player.Player.LoginPlayerInfo> players_ =
        java.util.Collections.emptyList();
      private void ensurePlayersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          players_ = new java.util.ArrayList<com.protos.player.Player.LoginPlayerInfo>(players_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.player.Player.LoginPlayerInfo, com.protos.player.Player.LoginPlayerInfo.Builder, com.protos.player.Player.LoginPlayerInfoOrBuilder> playersBuilder_;

      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public java.util.List<com.protos.player.Player.LoginPlayerInfo> getPlayersList() {
        if (playersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(players_);
        } else {
          return playersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public int getPlayersCount() {
        if (playersBuilder_ == null) {
          return players_.size();
        } else {
          return playersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public com.protos.player.Player.LoginPlayerInfo getPlayers(int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);
        } else {
          return playersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder setPlayers(
          int index, com.protos.player.Player.LoginPlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.set(index, value);
          onChanged();
        } else {
          playersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder setPlayers(
          int index, com.protos.player.Player.LoginPlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.set(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder addPlayers(com.protos.player.Player.LoginPlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(value);
          onChanged();
        } else {
          playersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder addPlayers(
          int index, com.protos.player.Player.LoginPlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(index, value);
          onChanged();
        } else {
          playersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder addPlayers(
          com.protos.player.Player.LoginPlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder addPlayers(
          int index, com.protos.player.Player.LoginPlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder addAllPlayers(
          java.lang.Iterable<? extends com.protos.player.Player.LoginPlayerInfo> values) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, players_);
          onChanged();
        } else {
          playersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder clearPlayers() {
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          playersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public Builder removePlayers(int index) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.remove(index);
          onChanged();
        } else {
          playersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public com.protos.player.Player.LoginPlayerInfo.Builder getPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public com.protos.player.Player.LoginPlayerInfoOrBuilder getPlayersOrBuilder(
          int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);  } else {
          return playersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public java.util.List<? extends com.protos.player.Player.LoginPlayerInfoOrBuilder> 
           getPlayersOrBuilderList() {
        if (playersBuilder_ != null) {
          return playersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(players_);
        }
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public com.protos.player.Player.LoginPlayerInfo.Builder addPlayersBuilder() {
        return getPlayersFieldBuilder().addBuilder(
            com.protos.player.Player.LoginPlayerInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public com.protos.player.Player.LoginPlayerInfo.Builder addPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().addBuilder(
            index, com.protos.player.Player.LoginPlayerInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.player.LoginPlayerInfo Players = 2;</code>
       */
      public java.util.List<com.protos.player.Player.LoginPlayerInfo.Builder> 
           getPlayersBuilderList() {
        return getPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.player.Player.LoginPlayerInfo, com.protos.player.Player.LoginPlayerInfo.Builder, com.protos.player.Player.LoginPlayerInfoOrBuilder> 
          getPlayersFieldBuilder() {
        if (playersBuilder_ == null) {
          playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.protos.player.Player.LoginPlayerInfo, com.protos.player.Player.LoginPlayerInfo.Builder, com.protos.player.Player.LoginPlayerInfoOrBuilder>(
                  players_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          players_ = null;
        }
        return playersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.account.LoginGameACK)
    }

    // @@protoc_insertion_point(class_scope:com.protos.account.LoginGameACK)
    private static final com.protos.account.Account.LoginGameACK DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.account.Account.LoginGameACK();
    }

    public static com.protos.account.Account.LoginGameACK getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginGameACK>
        PARSER = new com.google.protobuf.AbstractParser<LoginGameACK>() {
      public LoginGameACK parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginGameACK(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginGameACK> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGameACK> getParserForType() {
      return PARSER;
    }

    public com.protos.account.Account.LoginGameACK getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GpsInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.account.GpsInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * E
     * </pre>
     *
     * <code>float Latitude = 1;</code>
     */
    float getLatitude();

    /**
     * <pre>
     * N
     * </pre>
     *
     * <code>float Longitude = 2;</code>
     */
    float getLongitude();

    /**
     * <code>uint64 PlayerId = 3;</code>
     */
    long getPlayerId();
  }
  /**
   * <pre>
   * 发送Gps
   * </pre>
   *
   * Protobuf type {@code com.protos.account.GpsInfo}
   */
  public  static final class GpsInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.account.GpsInfo)
      GpsInfoOrBuilder {
    // Use GpsInfo.newBuilder() to construct.
    private GpsInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GpsInfo() {
      latitude_ = 0F;
      longitude_ = 0F;
      playerId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GpsInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              latitude_ = input.readFloat();
              break;
            }
            case 21: {

              longitude_ = input.readFloat();
              break;
            }
            case 24: {

              playerId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.account.Account.internal_static_com_protos_account_GpsInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.account.Account.internal_static_com_protos_account_GpsInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.account.Account.GpsInfo.class, com.protos.account.Account.GpsInfo.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private float latitude_;
    /**
     * <pre>
     * E
     * </pre>
     *
     * <code>float Latitude = 1;</code>
     */
    public float getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private float longitude_;
    /**
     * <pre>
     * N
     * </pre>
     *
     * <code>float Longitude = 2;</code>
     */
    public float getLongitude() {
      return longitude_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 3;
    private long playerId_;
    /**
     * <code>uint64 PlayerId = 3;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0F) {
        output.writeFloat(1, latitude_);
      }
      if (longitude_ != 0F) {
        output.writeFloat(2, longitude_);
      }
      if (playerId_ != 0L) {
        output.writeUInt64(3, playerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, latitude_);
      }
      if (longitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, longitude_);
      }
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, playerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.account.Account.GpsInfo)) {
        return super.equals(obj);
      }
      com.protos.account.Account.GpsInfo other = (com.protos.account.Account.GpsInfo) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getLatitude())
          == java.lang.Float.floatToIntBits(
              other.getLatitude()));
      result = result && (
          java.lang.Float.floatToIntBits(getLongitude())
          == java.lang.Float.floatToIntBits(
              other.getLongitude()));
      result = result && (getPlayerId()
          == other.getPlayerId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLatitude());
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLongitude());
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.account.Account.GpsInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.account.Account.GpsInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.GpsInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.account.Account.GpsInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.account.Account.GpsInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 发送Gps
     * </pre>
     *
     * Protobuf type {@code com.protos.account.GpsInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.account.GpsInfo)
        com.protos.account.Account.GpsInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.account.Account.internal_static_com_protos_account_GpsInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.account.Account.internal_static_com_protos_account_GpsInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.account.Account.GpsInfo.class, com.protos.account.Account.GpsInfo.Builder.class);
      }

      // Construct using com.protos.account.Account.GpsInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0F;

        longitude_ = 0F;

        playerId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.account.Account.internal_static_com_protos_account_GpsInfo_descriptor;
      }

      public com.protos.account.Account.GpsInfo getDefaultInstanceForType() {
        return com.protos.account.Account.GpsInfo.getDefaultInstance();
      }

      public com.protos.account.Account.GpsInfo build() {
        com.protos.account.Account.GpsInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.account.Account.GpsInfo buildPartial() {
        com.protos.account.Account.GpsInfo result = new com.protos.account.Account.GpsInfo(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.playerId_ = playerId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.account.Account.GpsInfo) {
          return mergeFrom((com.protos.account.Account.GpsInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.account.Account.GpsInfo other) {
        if (other == com.protos.account.Account.GpsInfo.getDefaultInstance()) return this;
        if (other.getLatitude() != 0F) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0F) {
          setLongitude(other.getLongitude());
        }
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.account.Account.GpsInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.account.Account.GpsInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float latitude_ ;
      /**
       * <pre>
       * E
       * </pre>
       *
       * <code>float Latitude = 1;</code>
       */
      public float getLatitude() {
        return latitude_;
      }
      /**
       * <pre>
       * E
       * </pre>
       *
       * <code>float Latitude = 1;</code>
       */
      public Builder setLatitude(float value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * E
       * </pre>
       *
       * <code>float Latitude = 1;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <pre>
       * N
       * </pre>
       *
       * <code>float Longitude = 2;</code>
       */
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <pre>
       * N
       * </pre>
       *
       * <code>float Longitude = 2;</code>
       */
      public Builder setLongitude(float value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * N
       * </pre>
       *
       * <code>float Longitude = 2;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0F;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <code>uint64 PlayerId = 3;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>uint64 PlayerId = 3;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 PlayerId = 3;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.account.GpsInfo)
    }

    // @@protoc_insertion_point(class_scope:com.protos.account.GpsInfo)
    private static final com.protos.account.Account.GpsInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.account.Account.GpsInfo();
    }

    public static com.protos.account.Account.GpsInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GpsInfo>
        PARSER = new com.google.protobuf.AbstractParser<GpsInfo>() {
      public GpsInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GpsInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GpsInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GpsInfo> getParserForType() {
      return PARSER;
    }

    public com.protos.account.Account.GpsInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_account_InitSocket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_account_InitSocket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_account_LoginGameREQ_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_account_LoginGameREQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_account_LoginGameACK_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_account_LoginGameACK_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_account_GpsInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_account_GpsInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\022com.protos.account\032\014pla" +
      "yer.proto\"\033\n\nInitSocket\022\r\n\005LType\030\001 \001(\r\">" +
      "\n\014LoginGameREQ\022\r\n\005Cdkey\030\001 \001(\t\022\020\n\010ServerI" +
      "D\030\002 \001(\r\022\r\n\005LType\030\003 \001(\r\"U\n\014LoginGameACK\022\020" +
      "\n\010ServerID\030\001 \001(\r\0223\n\007Players\030\002 \003(\0132\".com." +
      "protos.player.LoginPlayerInfo\"@\n\007GpsInfo" +
      "\022\020\n\010Latitude\030\001 \001(\002\022\021\n\tLongitude\030\002 \001(\002\022\020\n" +
      "\010PlayerId\030\003 \001(\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protos.player.Player.getDescriptor(),
        }, assigner);
    internal_static_com_protos_account_InitSocket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_account_InitSocket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_account_InitSocket_descriptor,
        new java.lang.String[] { "LType", });
    internal_static_com_protos_account_LoginGameREQ_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protos_account_LoginGameREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_account_LoginGameREQ_descriptor,
        new java.lang.String[] { "Cdkey", "ServerID", "LType", });
    internal_static_com_protos_account_LoginGameACK_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_protos_account_LoginGameACK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_account_LoginGameACK_descriptor,
        new java.lang.String[] { "ServerID", "Players", });
    internal_static_com_protos_account_GpsInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_protos_account_GpsInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_account_GpsInfo_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "PlayerId", });
    com.protos.player.Player.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
