// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.protos.chat;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatInfoREQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.chat.ChatInfoREQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
     * </pre>
     *
     * <code>uint32 channel = 2;</code>
     */
    int getChannel();

    /**
     * <pre>
     * 发送人名字
     * </pre>
     *
     * <code>string playerName = 3;</code>
     */
    java.lang.String getPlayerName();
    /**
     * <pre>
     * 发送人名字
     * </pre>
     *
     * <code>string playerName = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <pre>
     * 发送人id
     * </pre>
     *
     * <code>uint64 playerId = 4;</code>
     */
    long getPlayerId();
  }
  /**
   * <pre>
   *聊天信息
   * </pre>
   *
   * Protobuf type {@code com.protos.chat.ChatInfoREQ}
   */
  public  static final class ChatInfoREQ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.chat.ChatInfoREQ)
      ChatInfoREQOrBuilder {
    // Use ChatInfoREQ.newBuilder() to construct.
    private ChatInfoREQ(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatInfoREQ() {
      content_ = "";
      channel_ = 0;
      playerName_ = "";
      playerId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChatInfoREQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 16: {

              channel_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 32: {

              playerId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoREQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoREQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.chat.Chat.ChatInfoREQ.class, com.protos.chat.Chat.ChatInfoREQ.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    /**
     * <pre>
     * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
     * </pre>
     *
     * <code>uint32 channel = 2;</code>
     */
    public int getChannel() {
      return channel_;
    }

    public static final int PLAYERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object playerName_;
    /**
     * <pre>
     * 发送人名字
     * </pre>
     *
     * <code>string playerName = 3;</code>
     */
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送人名字
     * </pre>
     *
     * <code>string playerName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERID_FIELD_NUMBER = 4;
    private long playerId_;
    /**
     * <pre>
     * 发送人id
     * </pre>
     *
     * <code>uint64 playerId = 4;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      if (channel_ != 0) {
        output.writeUInt32(2, channel_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, playerName_);
      }
      if (playerId_ != 0L) {
        output.writeUInt64(4, playerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      if (channel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, channel_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, playerName_);
      }
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, playerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.chat.Chat.ChatInfoREQ)) {
        return super.equals(obj);
      }
      com.protos.chat.Chat.ChatInfoREQ other = (com.protos.chat.Chat.ChatInfoREQ) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getChannel()
          == other.getChannel());
      result = result && getPlayerName()
          .equals(other.getPlayerName());
      result = result && (getPlayerId()
          == other.getPlayerId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel();
      hash = (37 * hash) + PLAYERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatInfoREQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.chat.Chat.ChatInfoREQ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * Protobuf type {@code com.protos.chat.ChatInfoREQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.chat.ChatInfoREQ)
        com.protos.chat.Chat.ChatInfoREQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoREQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoREQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.chat.Chat.ChatInfoREQ.class, com.protos.chat.Chat.ChatInfoREQ.Builder.class);
      }

      // Construct using com.protos.chat.Chat.ChatInfoREQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = "";

        channel_ = 0;

        playerName_ = "";

        playerId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoREQ_descriptor;
      }

      public com.protos.chat.Chat.ChatInfoREQ getDefaultInstanceForType() {
        return com.protos.chat.Chat.ChatInfoREQ.getDefaultInstance();
      }

      public com.protos.chat.Chat.ChatInfoREQ build() {
        com.protos.chat.Chat.ChatInfoREQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.chat.Chat.ChatInfoREQ buildPartial() {
        com.protos.chat.Chat.ChatInfoREQ result = new com.protos.chat.Chat.ChatInfoREQ(this);
        result.content_ = content_;
        result.channel_ = channel_;
        result.playerName_ = playerName_;
        result.playerId_ = playerId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.chat.Chat.ChatInfoREQ) {
          return mergeFrom((com.protos.chat.Chat.ChatInfoREQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.chat.Chat.ChatInfoREQ other) {
        if (other == com.protos.chat.Chat.ChatInfoREQ.getDefaultInstance()) return this;
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getChannel() != 0) {
          setChannel(other.getChannel());
        }
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.chat.Chat.ChatInfoREQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.chat.Chat.ChatInfoREQ) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int channel_ ;
      /**
       * <pre>
       * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
       * </pre>
       *
       * <code>uint32 channel = 2;</code>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <pre>
       * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
       * </pre>
       *
       * <code>uint32 channel = 2;</code>
       */
      public Builder setChannel(int value) {
        
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
       * </pre>
       *
       * <code>uint32 channel = 2;</code>
       */
      public Builder clearChannel() {
        
        channel_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object playerName_ = "";
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public Builder clearPlayerName() {
        
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerName_ = value;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <pre>
       * 发送人id
       * </pre>
       *
       * <code>uint64 playerId = 4;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <pre>
       * 发送人id
       * </pre>
       *
       * <code>uint64 playerId = 4;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人id
       * </pre>
       *
       * <code>uint64 playerId = 4;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.chat.ChatInfoREQ)
    }

    // @@protoc_insertion_point(class_scope:com.protos.chat.ChatInfoREQ)
    private static final com.protos.chat.Chat.ChatInfoREQ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.chat.Chat.ChatInfoREQ();
    }

    public static com.protos.chat.Chat.ChatInfoREQ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatInfoREQ>
        PARSER = new com.google.protobuf.AbstractParser<ChatInfoREQ>() {
      public ChatInfoREQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatInfoREQ(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatInfoREQ> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatInfoREQ> getParserForType() {
      return PARSER;
    }

    public com.protos.chat.Chat.ChatInfoREQ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatInfoACKOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.chat.ChatInfoACK)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
     * </pre>
     *
     * <code>uint32 channel = 2;</code>
     */
    int getChannel();

    /**
     * <pre>
     * 发送人名字
     * </pre>
     *
     * <code>string playerName = 3;</code>
     */
    java.lang.String getPlayerName();
    /**
     * <pre>
     * 发送人名字
     * </pre>
     *
     * <code>string playerName = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <pre>
     * 发送人id
     * </pre>
     *
     * <code>uint64 playerId = 4;</code>
     */
    long getPlayerId();
  }
  /**
   * <pre>
   *聊天下发信息
   * </pre>
   *
   * Protobuf type {@code com.protos.chat.ChatInfoACK}
   */
  public  static final class ChatInfoACK extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.chat.ChatInfoACK)
      ChatInfoACKOrBuilder {
    // Use ChatInfoACK.newBuilder() to construct.
    private ChatInfoACK(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatInfoACK() {
      content_ = "";
      channel_ = 0;
      playerName_ = "";
      playerId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChatInfoACK(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 16: {

              channel_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 32: {

              playerId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoACK_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoACK_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.chat.Chat.ChatInfoACK.class, com.protos.chat.Chat.ChatInfoACK.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    /**
     * <pre>
     * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
     * </pre>
     *
     * <code>uint32 channel = 2;</code>
     */
    public int getChannel() {
      return channel_;
    }

    public static final int PLAYERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object playerName_;
    /**
     * <pre>
     * 发送人名字
     * </pre>
     *
     * <code>string playerName = 3;</code>
     */
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送人名字
     * </pre>
     *
     * <code>string playerName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERID_FIELD_NUMBER = 4;
    private long playerId_;
    /**
     * <pre>
     * 发送人id
     * </pre>
     *
     * <code>uint64 playerId = 4;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      if (channel_ != 0) {
        output.writeUInt32(2, channel_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, playerName_);
      }
      if (playerId_ != 0L) {
        output.writeUInt64(4, playerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      if (channel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, channel_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, playerName_);
      }
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, playerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.chat.Chat.ChatInfoACK)) {
        return super.equals(obj);
      }
      com.protos.chat.Chat.ChatInfoACK other = (com.protos.chat.Chat.ChatInfoACK) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getChannel()
          == other.getChannel());
      result = result && getPlayerName()
          .equals(other.getPlayerName());
      result = result && (getPlayerId()
          == other.getPlayerId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel();
      hash = (37 * hash) + PLAYERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.chat.Chat.ChatInfoACK parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatInfoACK parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.chat.Chat.ChatInfoACK prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *聊天下发信息
     * </pre>
     *
     * Protobuf type {@code com.protos.chat.ChatInfoACK}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.chat.ChatInfoACK)
        com.protos.chat.Chat.ChatInfoACKOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoACK_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoACK_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.chat.Chat.ChatInfoACK.class, com.protos.chat.Chat.ChatInfoACK.Builder.class);
      }

      // Construct using com.protos.chat.Chat.ChatInfoACK.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = "";

        channel_ = 0;

        playerName_ = "";

        playerId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatInfoACK_descriptor;
      }

      public com.protos.chat.Chat.ChatInfoACK getDefaultInstanceForType() {
        return com.protos.chat.Chat.ChatInfoACK.getDefaultInstance();
      }

      public com.protos.chat.Chat.ChatInfoACK build() {
        com.protos.chat.Chat.ChatInfoACK result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.chat.Chat.ChatInfoACK buildPartial() {
        com.protos.chat.Chat.ChatInfoACK result = new com.protos.chat.Chat.ChatInfoACK(this);
        result.content_ = content_;
        result.channel_ = channel_;
        result.playerName_ = playerName_;
        result.playerId_ = playerId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.chat.Chat.ChatInfoACK) {
          return mergeFrom((com.protos.chat.Chat.ChatInfoACK)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.chat.Chat.ChatInfoACK other) {
        if (other == com.protos.chat.Chat.ChatInfoACK.getDefaultInstance()) return this;
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getChannel() != 0) {
          setChannel(other.getChannel());
        }
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.chat.Chat.ChatInfoACK parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.chat.Chat.ChatInfoACK) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int channel_ ;
      /**
       * <pre>
       * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
       * </pre>
       *
       * <code>uint32 channel = 2;</code>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <pre>
       * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
       * </pre>
       *
       * <code>uint32 channel = 2;</code>
       */
      public Builder setChannel(int value) {
        
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 频道    其它--0 世界频道  -- 1 帮派频道  -- 2喇叭频道  -- 3* 公告频道  -- 4 队伍频道  -- 5
       * </pre>
       *
       * <code>uint32 channel = 2;</code>
       */
      public Builder clearChannel() {
        
        channel_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object playerName_ = "";
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public Builder clearPlayerName() {
        
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人名字
       * </pre>
       *
       * <code>string playerName = 3;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerName_ = value;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <pre>
       * 发送人id
       * </pre>
       *
       * <code>uint64 playerId = 4;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <pre>
       * 发送人id
       * </pre>
       *
       * <code>uint64 playerId = 4;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人id
       * </pre>
       *
       * <code>uint64 playerId = 4;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.chat.ChatInfoACK)
    }

    // @@protoc_insertion_point(class_scope:com.protos.chat.ChatInfoACK)
    private static final com.protos.chat.Chat.ChatInfoACK DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.chat.Chat.ChatInfoACK();
    }

    public static com.protos.chat.Chat.ChatInfoACK getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatInfoACK>
        PARSER = new com.google.protobuf.AbstractParser<ChatInfoACK>() {
      public ChatInfoACK parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatInfoACK(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatInfoACK> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatInfoACK> getParserForType() {
      return PARSER;
    }

    public com.protos.chat.Chat.ChatInfoACK getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatNoticeACKOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.chat.ChatNoticeACK)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 要不要加黑底
     * </pre>
     *
     * <code>bool special = 2;</code>
     */
    boolean getSpecial();
  }
  /**
   * <pre>
   *下推公告信息
   * </pre>
   *
   * Protobuf type {@code com.protos.chat.ChatNoticeACK}
   */
  public  static final class ChatNoticeACK extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.chat.ChatNoticeACK)
      ChatNoticeACKOrBuilder {
    // Use ChatNoticeACK.newBuilder() to construct.
    private ChatNoticeACK(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatNoticeACK() {
      content_ = "";
      special_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChatNoticeACK(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 16: {

              special_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.chat.Chat.internal_static_com_protos_chat_ChatNoticeACK_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.chat.Chat.internal_static_com_protos_chat_ChatNoticeACK_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.chat.Chat.ChatNoticeACK.class, com.protos.chat.Chat.ChatNoticeACK.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPECIAL_FIELD_NUMBER = 2;
    private boolean special_;
    /**
     * <pre>
     * 要不要加黑底
     * </pre>
     *
     * <code>bool special = 2;</code>
     */
    public boolean getSpecial() {
      return special_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      if (special_ != false) {
        output.writeBool(2, special_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      if (special_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, special_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.chat.Chat.ChatNoticeACK)) {
        return super.equals(obj);
      }
      com.protos.chat.Chat.ChatNoticeACK other = (com.protos.chat.Chat.ChatNoticeACK) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getSpecial()
          == other.getSpecial());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SPECIAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSpecial());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.chat.Chat.ChatNoticeACK parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.chat.Chat.ChatNoticeACK prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *下推公告信息
     * </pre>
     *
     * Protobuf type {@code com.protos.chat.ChatNoticeACK}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.chat.ChatNoticeACK)
        com.protos.chat.Chat.ChatNoticeACKOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatNoticeACK_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatNoticeACK_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.chat.Chat.ChatNoticeACK.class, com.protos.chat.Chat.ChatNoticeACK.Builder.class);
      }

      // Construct using com.protos.chat.Chat.ChatNoticeACK.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = "";

        special_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.chat.Chat.internal_static_com_protos_chat_ChatNoticeACK_descriptor;
      }

      public com.protos.chat.Chat.ChatNoticeACK getDefaultInstanceForType() {
        return com.protos.chat.Chat.ChatNoticeACK.getDefaultInstance();
      }

      public com.protos.chat.Chat.ChatNoticeACK build() {
        com.protos.chat.Chat.ChatNoticeACK result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.chat.Chat.ChatNoticeACK buildPartial() {
        com.protos.chat.Chat.ChatNoticeACK result = new com.protos.chat.Chat.ChatNoticeACK(this);
        result.content_ = content_;
        result.special_ = special_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.chat.Chat.ChatNoticeACK) {
          return mergeFrom((com.protos.chat.Chat.ChatNoticeACK)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.chat.Chat.ChatNoticeACK other) {
        if (other == com.protos.chat.Chat.ChatNoticeACK.getDefaultInstance()) return this;
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getSpecial() != false) {
          setSpecial(other.getSpecial());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.chat.Chat.ChatNoticeACK parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.chat.Chat.ChatNoticeACK) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private boolean special_ ;
      /**
       * <pre>
       * 要不要加黑底
       * </pre>
       *
       * <code>bool special = 2;</code>
       */
      public boolean getSpecial() {
        return special_;
      }
      /**
       * <pre>
       * 要不要加黑底
       * </pre>
       *
       * <code>bool special = 2;</code>
       */
      public Builder setSpecial(boolean value) {
        
        special_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 要不要加黑底
       * </pre>
       *
       * <code>bool special = 2;</code>
       */
      public Builder clearSpecial() {
        
        special_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protos.chat.ChatNoticeACK)
    }

    // @@protoc_insertion_point(class_scope:com.protos.chat.ChatNoticeACK)
    private static final com.protos.chat.Chat.ChatNoticeACK DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.chat.Chat.ChatNoticeACK();
    }

    public static com.protos.chat.Chat.ChatNoticeACK getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatNoticeACK>
        PARSER = new com.google.protobuf.AbstractParser<ChatNoticeACK>() {
      public ChatNoticeACK parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatNoticeACK(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatNoticeACK> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatNoticeACK> getParserForType() {
      return PARSER;
    }

    public com.protos.chat.Chat.ChatNoticeACK getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_chat_ChatInfoREQ_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_chat_ChatInfoREQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_chat_ChatInfoACK_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_chat_ChatInfoACK_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_chat_ChatNoticeACK_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_chat_ChatNoticeACK_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\017com.protos.chat\"U\n\013ChatInf" +
      "oREQ\022\017\n\007content\030\001 \001(\t\022\017\n\007channel\030\002 \001(\r\022\022" +
      "\n\nplayerName\030\003 \001(\t\022\020\n\010playerId\030\004 \001(\004\"U\n\013" +
      "ChatInfoACK\022\017\n\007content\030\001 \001(\t\022\017\n\007channel\030" +
      "\002 \001(\r\022\022\n\nplayerName\030\003 \001(\t\022\020\n\010playerId\030\004 " +
      "\001(\004\"1\n\rChatNoticeACK\022\017\n\007content\030\001 \001(\t\022\017\n" +
      "\007special\030\002 \001(\010b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protos_chat_ChatInfoREQ_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_chat_ChatInfoREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_chat_ChatInfoREQ_descriptor,
        new java.lang.String[] { "Content", "Channel", "PlayerName", "PlayerId", });
    internal_static_com_protos_chat_ChatInfoACK_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protos_chat_ChatInfoACK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_chat_ChatInfoACK_descriptor,
        new java.lang.String[] { "Content", "Channel", "PlayerName", "PlayerId", });
    internal_static_com_protos_chat_ChatNoticeACK_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_protos_chat_ChatNoticeACK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_chat_ChatNoticeACK_descriptor,
        new java.lang.String[] { "Content", "Special", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
